/* Generated by with --emit-c (conservative MIR subset). */
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <locale.h>
#include <stdio.h>
#include <time.h>
#ifndef _WIN32
#include <unistd.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <fcntl.h>
#else
#include <io.h>
#include <sys/stat.h>
#endif
#include "with_runtime.h"

/* Extra runtime declarations */
#define fmt_buf_new with_fmt_buf_new
#define fmt_buf_write_str with_fmt_buf_write_str
#define fmt_buf_finish with_fmt_buf_finish
extern uint8_t* with_fmt_buf_new(void);
extern void with_fmt_buf_write_str(uint8_t*, with_str);
extern void with_fmt_buf_write_i64_spec(uint8_t*, int64_t, int32_t, int64_t, int32_t, int32_t, int32_t);
extern void with_fmt_buf_write_f64_spec(uint8_t*, double, int64_t, int32_t, int32_t, int32_t);
extern void with_fmt_buf_write_str_spec(uint8_t*, with_str, int64_t, int32_t, int32_t);
extern with_str with_fmt_buf_finish(uint8_t*);
extern void* with_alloc(int64_t);
extern void with_free(uint8_t*);
extern void* with_memcpy(void*, void*, int64_t);
extern void* with_memset(void*, int32_t, int64_t);
extern int64_t with_clock_nanos(void);
extern int32_t with_nanosleep(int64_t);
extern double with_parse_float(with_str);
extern with_str with_sysinfo_os(void);
extern with_str with_sysinfo_arch(void);
extern with_str with_sysinfo_hostname(void);
extern with_str with_str_trim(with_str);
extern with_str with_str_clone(with_str);

#ifdef WITH_BOOTSTRAP_TYPES_H
extern with_str with_str_concat(with_str, with_str);
extern int64_t with_str_len(with_str);
extern int32_t with_str_byte_at(with_str, int64_t);
extern with_str with_str_from_cstr(uint8_t*);
extern with_str with_str_from_bytes(uint8_t*, int64_t);
extern with_str with_i64_to_str(int64_t);
extern with_str with_fmt_u32(uint32_t);
extern with_str with_fmt_u64(uint64_t);
extern with_str with_bool_to_str(int32_t);
extern void with_println_bool(int32_t);
extern void with_ewrite(with_str);
extern void with_panic(with_str, with_str, int32_t);
extern int32_t with_fiber_in_fiber(void);
extern void with_fiber_await(int32_t);
#endif
extern void with_fiber_panic_capture(uint8_t*, int32_t);

static int32_t __with_global_interrupt_flag__108 = ((int32_t)(((uint64_t)0x0ULL)));
static int64_t __with_global_last_spawned_handle__109 = ((int64_t)(((uint64_t)0x0ULL)));
static uint8_t __with_global_cmd_buf__110[32768] = {0};

extern int32_t CreateProcessA(uint8_t* _1, uint8_t* _2, uint8_t* _3, uint8_t* _4, int32_t _5, uint32_t _6, uint8_t* _7, uint8_t* _8, uint8_t* _9, uint8_t* _10);
extern uint32_t WaitForSingleObject(int64_t _1, uint32_t _2);
extern int32_t GetExitCodeProcess(int64_t _1, uint32_t* _2);
extern int32_t TerminateProcess(int64_t _1, uint32_t _2);
extern int32_t CloseHandle(int64_t _1);
extern int64_t CreateFileA(uint8_t* _1, uint32_t _2, uint32_t _3, uint8_t* _4, uint32_t _5, uint32_t _6, int64_t _7);
extern int32_t SetEnvironmentVariableA(uint8_t* _1, uint8_t* _2);
extern uint32_t GetLastError(void);

with_str make_str__111(uint8_t* _1, int64_t _2);
uint8_t* str_to_c_buf__115(with_str _1);
int64_t cstr_len__120(uint8_t* _1);
int32_t win_last_error__121();
int64_t store_i64__122(int64_t _1, int64_t _2, int64_t _3);
uint32_t load_u32__126(int64_t _1, int64_t _2);
int64_t load_i64__127(int64_t _1, int64_t _2);
uint32_t store_u32__128(int64_t _1, int64_t _2, uint32_t _3);
int32_t store_i32__129(int64_t _1, int64_t _2, int32_t _3);
uint8_t* build_command_line_from_blob__130(uint8_t* _1, int64_t _2);
uint8_t* first_arg_from_blob__136(uint8_t* _1, int64_t _2);
uint32_t fill_startupinfo__137(uint8_t* _1, int64_t _2, int64_t _3, int64_t _4);
int64_t create_file_for_redirect__142(uint8_t* _1, int32_t _2);
void win32_close__145(int64_t _1);
int32_t wait_for_process_timeout__147(int64_t _1, int64_t _2, int32_t _3);
int32_t run_binary_direct__153(uint8_t* _1);
int32_t run_argv_direct_cwd__158(uint8_t* _1, int64_t _2, uint8_t* _3);
int32_t run_argv_direct__161(uint8_t* _1, int64_t _2);
int32_t run_argv_capture_cwd__162(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4, int32_t _5, uint8_t* _6, uint8_t* _7);
int32_t spawn_argv_capture__169(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4);
int32_t run_argv_capture__171(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4, int32_t _5);
int32_t run_argv_capture_input__172(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4, int32_t _5, uint8_t* _6);
int32_t with_setenv_str(with_str _1, with_str _2);
void with_install_interrupt_handlers();
void with_raise_stack_limit();
int32_t with_interrupt_requested();
int32_t with_exec_binary(with_str _1);
int32_t with_exec_argv(with_str _1);
int32_t with_exec_argv_cwd(with_str _1, with_str _2);
int32_t with_exec_argv_capture(with_str _1, with_str _2, with_str _3, int32_t _4);
int32_t with_exec_argv_capture_input(with_str _1, with_str _2, with_str _3, int32_t _4, with_str _5);
int32_t with_exec_argv_capture_cwd(with_str _1, with_str _2, with_str _3, int32_t _4, with_str _5);
int32_t with_exec_argv_capture_spawn(with_str _1, with_str _2, with_str _3);
int32_t with_exec_wait(int32_t _1, int32_t _2);

with_str make_str__111(uint8_t* _1, int64_t _2) {
    with_str _0 __attribute__((unused)) = {0};
    int64_t _3[2] __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int64_t _5[2] __attribute__((unused)) = {0};
    with_str* _6 __attribute__((unused)) = {0};
    void* _7 __attribute__((unused)) = {0};
    with_str* _8 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 88 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 89 "rt\compat_runtime_windows.w"
    /* StorageLive(_3); */
    _4 = ((int64_t)(_1));
    { int64_t __with_arr_tmp[2] = {_4, _2}; memcpy(_5, __with_arr_tmp, sizeof(_5)); }
    memcpy(_3, _5, sizeof(_3));
#line 90 "rt\compat_runtime_windows.w"
    /* StorageLive(_6); */
    _7 = (&_3);
    _8 = (with_str*)((with_str*)(_7));
    _6 = _8;
#line 91 "rt\compat_runtime_windows.w"
    _0 = (*_6);
    return _0;
}

uint8_t* str_to_c_buf__115(with_str _1) {
    uint8_t* _0 __attribute__((unused)) = {0};
    uint8_t* _2 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    uint8_t* _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    bool _7 __attribute__((unused)) = {0};
    uint8_t* _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    bool _10 __attribute__((unused)) = {0};
    uint8_t** _11 __attribute__((unused)) = {0};
    with_str* _12 __attribute__((unused)) = {0};
    uint8_t** _13 __attribute__((unused)) = {0};
    uint8_t* _14 __attribute__((unused)) = {0};
    int64_t _15 __attribute__((unused)) = {0};
    int32_t _16 __attribute__((unused)) = {0};
    int64_t _17 __attribute__((unused)) = {0};
    int64_t _18 __attribute__((unused)) = {0};
    int64_t _19 __attribute__((unused)) = {0};
    uint8_t* _20 __attribute__((unused)) = {0};
    uint8_t* _21 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 93 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
#line 94 "rt\compat_runtime_windows.w"
    /* StorageLive(_2); */
    _3 = ((_1).len);
    goto bb1;
bb1:
    _4 = (_3 + 1);
    _5 = with_alloc(_4);
    goto bb2;
bb2:
    _2 = _5;
#line 95 "rt\compat_runtime_windows.w"
    _6 = ((int64_t)(_2));
    _7 = (_6 == 0);
    if (_7 == 1) {
        goto bb3;
    }
    else {
        goto bb4;
    }
bb3:
#line 96 "rt\compat_runtime_windows.w"
    _8 = (uint8_t*)((uint8_t*)(0));
    _0 = _8;
    return _0;
bb4:
    goto bb5;
bb5:
    _9 = ((_1).len);
    goto bb7;
bb6:
    goto bb5;
bb7:
#line 97 "rt\compat_runtime_windows.w"
    _10 = (_9 > 0);
    if (_10 == 1) {
        goto bb8;
    }
    else {
        goto bb9;
    }
bb8:
#line 98 "rt\compat_runtime_windows.w"
    /* StorageLive(_11); */
    _12 = (&_1);
    _13 = (uint8_t**)((uint8_t**)(_12));
    _11 = _13;
#line 99 "rt\compat_runtime_windows.w"
    /* StorageLive(_14); */
    _14 = (*_11);
    _15 = ((_1).len);
    goto bb11;
bb9:
    goto bb10;
bb10:
#line 101 "rt\compat_runtime_windows.w"
    _17 = ((int64_t)(_2));
    _18 = ((_1).len);
    goto bb13;
bb11:
    with_memcpy(_2, _14, _15);
    goto bb12;
bb12:
    goto bb10;
bb13:
    _19 = (_17 + _18);
    _20 = (uint8_t*)((uint8_t*)(_19));
    _21 = _20;
    (*_21) = 0;
#line 102 "rt\compat_runtime_windows.w"
    _0 = _2;
    return _0;
bb14: ;
bb15: ;
bb16: ;
bb17: ;
bb18: ;
bb19: ;
bb20: ;
bb21: ;
bb22: ;
bb23: ;
bb24: ;
bb25: ;
bb26: ;
bb27: ;
bb28: ;
}

int64_t cstr_len__120(uint8_t* _1) {
    int64_t _0 __attribute__((unused)) = {0};
    int64_t _2 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int64_t _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    uint8_t* _8 __attribute__((unused)) = {0};
    bool _9 __attribute__((unused)) = {0};
    int64_t _10 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 104 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
#line 105 "rt\compat_runtime_windows.w"
    _2 = ((int64_t)(_1));
    _3 = (_2 == 0);
    if (_3 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
#line 106 "rt\compat_runtime_windows.w"
    _0 = 0;
    return _0;
bb2:
    goto bb3;
bb3:
#line 107 "rt\compat_runtime_windows.w"
    /* StorageLive(_4); */
    _4 = 0;
    goto bb5;
bb4:
    goto bb3;
bb5:
#line 108 "rt\compat_runtime_windows.w"
    _5 = ((int64_t)(_1));
    _6 = (_5 + _4);
    _7 = (uint8_t*)((uint8_t*)(_6));
    _8 = _7;
    _9 = ((*_8) != 0);
    if (_9 == 1) {
        goto bb6;
    }
    else {
        goto bb7;
    }
bb6:
#line 109 "rt\compat_runtime_windows.w"
    _10 = (_4 + 1);
    _4 = _10;
    goto bb5;
bb7:
#line 110 "rt\compat_runtime_windows.w"
    _0 = _4;
    return _0;
}

int32_t win_last_error__121() {
    int32_t _0 __attribute__((unused)) = {0};
    uint32_t _1 __attribute__((unused)) = {0};
    int32_t _2 __attribute__((unused)) = {0};
    goto bb0;
bb0:
    _1 = GetLastError();
    goto bb1;
bb1:
#line 113 "rt\compat_runtime_windows.w"
    _2 = ((int32_t)(_1));
    _0 = _2;
    return _0;
}

int64_t store_i64__122(int64_t _1, int64_t _2, int64_t _3) {
    int64_t _0 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int64_t* _5 __attribute__((unused)) = {0};
    int64_t* _6 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 115 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
#line 116 "rt\compat_runtime_windows.w"
    _4 = (_1 + _2);
    _5 = (int64_t*)((int64_t*)(_4));
    _6 = _5;
    (*_6) = _3;
    _0 = _3;
    return _0;
}

uint32_t load_u32__126(int64_t _1, int64_t _2) {
    uint32_t _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    uint32_t* _4 __attribute__((unused)) = {0};
    uint32_t* _5 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 118 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 119 "rt\compat_runtime_windows.w"
    _3 = (_1 + _2);
    _4 = (uint32_t*)((uint32_t*)(_3));
    _5 = _4;
    _0 = (*_5);
    return _0;
}

int64_t load_i64__127(int64_t _1, int64_t _2) {
    int64_t _0 __attribute__((unused)) = {0};
    int64_t _3 __attribute__((unused)) = {0};
    int64_t* _4 __attribute__((unused)) = {0};
    int64_t* _5 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 121 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 122 "rt\compat_runtime_windows.w"
    _3 = (_1 + _2);
    _4 = (int64_t*)((int64_t*)(_3));
    _5 = _4;
    _0 = (*_5);
    return _0;
}

uint32_t store_u32__128(int64_t _1, int64_t _2, uint32_t _3) {
    uint32_t _0 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    uint32_t* _5 __attribute__((unused)) = {0};
    uint32_t* _6 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 124 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
#line 125 "rt\compat_runtime_windows.w"
    _4 = (_1 + _2);
    _5 = (uint32_t*)((uint32_t*)(_4));
    _6 = _5;
    (*_6) = _3;
    _0 = _3;
    return _0;
}

int32_t store_i32__129(int64_t _1, int64_t _2, int32_t _3) {
    int32_t _0 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    int32_t* _5 __attribute__((unused)) = {0};
    int32_t* _6 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 127 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
#line 128 "rt\compat_runtime_windows.w"
    _4 = (_1 + _2);
    _5 = (int32_t*)((int32_t*)(_4));
    _6 = _5;
    (*_6) = _3;
    _0 = _3;
    return _0;
}

uint8_t* build_command_line_from_blob__130(uint8_t* _1, int64_t _2) {
    uint8_t* _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    uint8_t _4[1] __attribute__((unused)) = {0};
    uint8_t _5 __attribute__((unused)) = {0};
    uint8_t _6[1] __attribute__((unused)) = {0};
    void* _7 __attribute__((unused)) = {0};
    uint8_t** _8 __attribute__((unused)) = {0};
    uint8_t* _9 __attribute__((unused)) = {0};
    int64_t _10 __attribute__((unused)) = {0};
    int64_t _11 __attribute__((unused)) = {0};
    bool _12 __attribute__((unused)) = {0};
    bool _13 __attribute__((unused)) = {0};
    bool _14 __attribute__((unused)) = {0};
    bool _15 __attribute__((unused)) = {0};
    bool _16 __attribute__((unused)) = {0};
    void* _18 __attribute__((unused)) = {0};
    int64_t _19 __attribute__((unused)) = {0};
    int64_t _20 __attribute__((unused)) = {0};
    uint8_t* _21 __attribute__((unused)) = {0};
    uint8_t* _22 __attribute__((unused)) = {0};
    int64_t _23 __attribute__((unused)) = {0};
    bool _24 __attribute__((unused)) = {0};
    bool _25 __attribute__((unused)) = {0};
    int64_t _26 __attribute__((unused)) = {0};
    int64_t _27 __attribute__((unused)) = {0};
    uint8_t* _28 __attribute__((unused)) = {0};
    uint8_t* _29 __attribute__((unused)) = {0};
    bool _30 __attribute__((unused)) = {0};
    uint8_t _31 __attribute__((unused)) = {0};
    int64_t _32 __attribute__((unused)) = {0};
    int64_t _33 __attribute__((unused)) = {0};
    uint8_t* _34 __attribute__((unused)) = {0};
    uint8_t* _35 __attribute__((unused)) = {0};
    void* _37 __attribute__((unused)) = {0};
    int64_t _38 __attribute__((unused)) = {0};
    int64_t _39 __attribute__((unused)) = {0};
    uint8_t* _40 __attribute__((unused)) = {0};
    uint8_t* _41 __attribute__((unused)) = {0};
    int64_t _42 __attribute__((unused)) = {0};
    int64_t _43 __attribute__((unused)) = {0};
    bool _44 __attribute__((unused)) = {0};
    int64_t _45 __attribute__((unused)) = {0};
    void* _47 __attribute__((unused)) = {0};
    int64_t _48 __attribute__((unused)) = {0};
    int64_t _49 __attribute__((unused)) = {0};
    uint8_t* _50 __attribute__((unused)) = {0};
    uint8_t* _51 __attribute__((unused)) = {0};
    void* _52 __attribute__((unused)) = {0};
    uint8_t** _53 __attribute__((unused)) = {0};
    uint8_t* _54 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 133 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 134 "rt\compat_runtime_windows.w"
    _3 = (_2 <= 0);
    if (_3 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
#line 135 "rt\compat_runtime_windows.w"
    /* StorageLive(_4); */
    _5 = ((uint8_t)(0));
    { uint8_t __with_arr_tmp[1] = {_5}; memcpy(_6, __with_arr_tmp, sizeof(_6)); }
    memcpy(_4, _6, sizeof(_4));
#line 136 "rt\compat_runtime_windows.w"
    _7 = (&_4);
    _8 = (uint8_t**)((uint8_t**)(_7));
    _9 = (uint8_t*)((uint8_t*)(_8));
    _0 = _9;
    return _0;
bb2:
    goto bb3;
bb3:
#line 137 "rt\compat_runtime_windows.w"
    /* StorageLive(_10); */
    _10 = 0;
#line 138 "rt\compat_runtime_windows.w"
    /* StorageLive(_11); */
    _11 = 0;
#line 139 "rt\compat_runtime_windows.w"
    /* StorageLive(_12); */
    _12 = true;
    goto bb5;
bb4:
    goto bb3;
bb5:
#line 140 "rt\compat_runtime_windows.w"
    _14 = (_11 < _2);
    _13 = _14;
    if (_13 == 1) {
        goto bb8;
    }
    else {
        goto bb9;
    }
bb6:
#line 141 "rt\compat_runtime_windows.w"
    _16 = (!(_12));
    if (_16 == 1) {
        goto bb10;
    }
    else {
        goto bb11;
    }
bb7:
#line 153 "rt\compat_runtime_windows.w"
    _47 = (&__with_global_cmd_buf__110);
    _48 = ((int64_t)(_47));
    _49 = (_48 + _10);
    _50 = (uint8_t*)((uint8_t*)(_49));
    _51 = _50;
    (*_51) = 0;
#line 154 "rt\compat_runtime_windows.w"
    _52 = (&__with_global_cmd_buf__110);
    _53 = (uint8_t**)((uint8_t**)(_52));
    _54 = (uint8_t*)((uint8_t*)(_53));
    _0 = _54;
    return _0;
bb8:
#line 140 "rt\compat_runtime_windows.w"
    _15 = (_10 < 32760);
    _13 = _15;
    goto bb9;
bb9:
    if (_13 == 1) {
        goto bb6;
    }
    else {
        goto bb7;
    }
bb10:
#line 142 "rt\compat_runtime_windows.w"
    _18 = (&__with_global_cmd_buf__110);
    _19 = ((int64_t)(_18));
    _20 = (_19 + _10);
    _21 = (uint8_t*)((uint8_t*)(_20));
    _22 = _21;
    (*_22) = 32;
#line 143 "rt\compat_runtime_windows.w"
    _23 = (_10 + 1);
    _10 = _23;
    goto bb12;
bb11:
    goto bb12;
bb12:
#line 144 "rt\compat_runtime_windows.w"
    _12 = false;
    goto bb13;
bb13:
#line 145 "rt\compat_runtime_windows.w"
    _25 = (_11 < _2);
    _24 = _25;
    if (_24 == 1) {
        goto bb16;
    }
    else {
        goto bb17;
    }
bb14:
#line 146 "rt\compat_runtime_windows.w"
    /* StorageLive(_31); */
    _32 = ((int64_t)(_1));
    _33 = (_32 + _11);
    _34 = (uint8_t*)((uint8_t*)(_33));
    _35 = _34;
    _31 = (*_35);
#line 147 "rt\compat_runtime_windows.w"
    _37 = (&__with_global_cmd_buf__110);
    _38 = ((int64_t)(_37));
    _39 = (_38 + _10);
    _40 = (uint8_t*)((uint8_t*)(_39));
    _41 = _40;
    (*_41) = _31;
#line 148 "rt\compat_runtime_windows.w"
    _42 = (_10 + 1);
    _10 = _42;
#line 149 "rt\compat_runtime_windows.w"
    _43 = (_11 + 1);
    _11 = _43;
#line 150 "rt\compat_runtime_windows.w"
    _44 = (_10 >= 32760);
    if (_44 == 1) {
        goto bb18;
    }
    else {
        goto bb19;
    }
bb15:
#line 152 "rt\compat_runtime_windows.w"
    _45 = (_11 + 1);
    _11 = _45;
    goto bb5;
bb16:
#line 145 "rt\compat_runtime_windows.w"
    _26 = ((int64_t)(_1));
    _27 = (_26 + _11);
    _28 = (uint8_t*)((uint8_t*)(_27));
    _29 = _28;
    _30 = ((*_29) != 0);
    _24 = _30;
    goto bb17;
bb17:
    if (_24 == 1) {
        goto bb14;
    }
    else {
        goto bb15;
    }
bb18:
    goto bb15;
bb19:
    goto bb20;
bb20:
    goto bb13;
bb21:
    goto bb20;
}

uint8_t* first_arg_from_blob__136(uint8_t* _1, int64_t _2) {
    uint8_t* _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    uint8_t* _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 157 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 158 "rt\compat_runtime_windows.w"
    _3 = (_2 <= 0);
    if (_3 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
#line 159 "rt\compat_runtime_windows.w"
    _4 = (uint8_t*)((uint8_t*)(0));
    _0 = _4;
    return _0;
bb2:
    goto bb3;
bb3:
#line 160 "rt\compat_runtime_windows.w"
    _0 = _1;
    return _0;
bb4:
    goto bb3;
}

uint32_t fill_startupinfo__137(uint8_t* _1, int64_t _2, int64_t _3, int64_t _4) {
    uint32_t _0 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    int32_t _6 __attribute__((unused)) = {0};
    int64_t _7 __attribute__((unused)) = {0};
    uint32_t _8 __attribute__((unused)) = {0};
    uint32_t _9 __attribute__((unused)) = {0};
    uint32_t _10 __attribute__((unused)) = {0};
    bool _11 __attribute__((unused)) = {0};
    int64_t _12 __attribute__((unused)) = {0};
    int64_t _13 __attribute__((unused)) = {0};
    uint32_t _14 __attribute__((unused)) = {0};
    bool _15 __attribute__((unused)) = {0};
    int64_t _16 __attribute__((unused)) = {0};
    int64_t _17 __attribute__((unused)) = {0};
    uint32_t _18 __attribute__((unused)) = {0};
    bool _19 __attribute__((unused)) = {0};
    int64_t _20 __attribute__((unused)) = {0};
    int64_t _21 __attribute__((unused)) = {0};
    uint32_t _22 __attribute__((unused)) = {0};
    int64_t _23 __attribute__((unused)) = {0};
    uint32_t _24 __attribute__((unused)) = {0};
    int64_t _25 __attribute__((unused)) = {0};
    uint32_t _26 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 163 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
#line 164 "rt\compat_runtime_windows.w"
    _5 = ((int32_t)(104));
    with_memset(_1, 0, _5);
    goto bb1;
bb1:
#line 165 "rt\compat_runtime_windows.w"
    _7 = ((int64_t)(_1));
    _8 = ((uint32_t)(104));
    _9 = store_u32__128(_7, 0, _8);
    goto bb2;
bb2:
#line 166 "rt\compat_runtime_windows.w"
    /* StorageLive(_10); */
    _10 = 0;
#line 167 "rt\compat_runtime_windows.w"
    _11 = (_2 != -1);
    if (_11 == 1) {
        goto bb3;
    }
    else {
        goto bb4;
    }
bb3:
#line 168 "rt\compat_runtime_windows.w"
    _12 = ((int64_t)(_1));
    _13 = store_i64__122(_12, 80, _2);
    goto bb6;
bb4:
    goto bb5;
bb5:
#line 170 "rt\compat_runtime_windows.w"
    _15 = (_3 != -1);
    if (_15 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb6:
#line 169 "rt\compat_runtime_windows.w"
    _14 = (_10 | 256);
    _10 = _14;
    goto bb5;
bb7:
#line 171 "rt\compat_runtime_windows.w"
    _16 = ((int64_t)(_1));
    _17 = store_i64__122(_16, 88, _3);
    goto bb10;
bb8:
    goto bb9;
bb9:
#line 173 "rt\compat_runtime_windows.w"
    _19 = (_4 != -1);
    if (_19 == 1) {
        goto bb11;
    }
    else {
        goto bb12;
    }
bb10:
#line 172 "rt\compat_runtime_windows.w"
    _18 = (_10 | 256);
    _10 = _18;
    goto bb9;
bb11:
#line 174 "rt\compat_runtime_windows.w"
    _20 = ((int64_t)(_1));
    _21 = store_i64__122(_20, 96, _4);
    goto bb14;
bb12:
    goto bb13;
bb13:
#line 176 "rt\compat_runtime_windows.w"
    _23 = ((int64_t)(_1));
    _24 = store_u32__128(_23, 60, _10);
    goto bb15;
bb14:
#line 175 "rt\compat_runtime_windows.w"
    _22 = (_10 | 256);
    _10 = _22;
    goto bb13;
bb15:
#line 177 "rt\compat_runtime_windows.w"
    _25 = ((int64_t)(_1));
    _26 = store_u32__128(_25, 64, 0);
    goto bb16;
bb16:
    _0 = _26;
    return _0;
bb17: ;
bb18: ;
bb19: ;
bb20: ;
bb21: ;
bb22: ;
bb23: ;
bb24: ;
bb25: ;
bb26: ;
bb27: ;
bb28: ;
bb29: ;
bb30: ;
bb31: ;
bb32: ;
bb33: ;
bb34: ;
bb35: ;
bb36: ;
bb37: ;
bb38: ;
bb39: ;
bb40: ;
bb41: ;
}

int64_t create_file_for_redirect__142(uint8_t* _1, int32_t _2) {
    int64_t _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    uint8_t* _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    int64_t _8 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 179 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 180 "rt\compat_runtime_windows.w"
    _3 = (_2 != 0);
    if (_3 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
#line 181 "rt\compat_runtime_windows.w"
    _5 = (uint8_t*)((uint8_t*)(0));
    _6 = CreateFileA(_1, 1073741824, 1, _5, 2, 128, 0);
    goto bb4;
bb2:
#line 183 "rt\compat_runtime_windows.w"
    _7 = (uint8_t*)((uint8_t*)(0));
    _8 = CreateFileA(_1, 2147483648, 1, _7, 3, 128, 0);
    goto bb5;
bb3:
    _0 = _4;
    return _0;
bb4:
#line 181 "rt\compat_runtime_windows.w"
    _4 = _6;
    goto bb3;
bb5:
#line 180 "rt\compat_runtime_windows.w"
    _4 = _8;
    goto bb3;
bb6: ;
bb7: ;
bb8: ;
}

void win32_close__145(int64_t _1) {
    int32_t _0 __attribute__((unused)) = {0};
    bool _2 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    bool _4 __attribute__((unused)) = {0};
    int32_t _5 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 185 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
#line 186 "rt\compat_runtime_windows.w"
    _3 = (_1 != -1);
    _2 = _3;
    if (_2 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
    _4 = (_1 != 0);
    _2 = _4;
    goto bb2;
bb2:
    if (_2 == 1) {
        goto bb3;
    }
    else {
        goto bb4;
    }
bb3:
    _5 = CloseHandle(_1);
    goto bb6;
bb4:
    goto bb5;
bb5:
    return;
bb6:
    goto bb5;
bb7: ;
bb8: ;
}

int32_t wait_for_process_timeout__147(int64_t _1, int64_t _2, int32_t _3) {
    int32_t _0 __attribute__((unused)) = {0};
    uint32_t _4 __attribute__((unused)) = {0};
    bool _5 __attribute__((unused)) = {0};
    uint32_t _6 __attribute__((unused)) = {0};
    uint32_t _7 __attribute__((unused)) = {0};
    uint32_t _8 __attribute__((unused)) = {0};
    uint32_t _9 __attribute__((unused)) = {0};
    bool _10 __attribute__((unused)) = {0};
    uint32_t _11 __attribute__((unused)) = {0};
    uint32_t* _12 __attribute__((unused)) = {0};
    int32_t _13 __attribute__((unused)) = {0};
    int32_t _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    int32_t _16 __attribute__((unused)) = {0};
    bool _17 __attribute__((unused)) = {0};
    uint32_t _18 __attribute__((unused)) = {0};
    int32_t _19 __attribute__((unused)) = {0};
    uint32_t _20 __attribute__((unused)) = {0};
    uint32_t* _21 __attribute__((unused)) = {0};
    int32_t _22 __attribute__((unused)) = {0};
    int32_t _23 __attribute__((unused)) = {0};
    int32_t _24 __attribute__((unused)) = {0};
    int32_t _25 __attribute__((unused)) = {0};
    int32_t _26 __attribute__((unused)) = {0};
    int32_t _27 __attribute__((unused)) = {0};
    int32_t _28 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 190 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
#line 191 "rt\compat_runtime_windows.w"
    /* StorageLive(_4); */
    _5 = (_3 < 0);
    if (_5 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
    _6 = 4294967295;
    goto bb3;
bb2:
    _7 = ((uint32_t)(_3));
    _6 = _7;
    goto bb3;
bb3:
    _4 = _6;
#line 192 "rt\compat_runtime_windows.w"
    /* StorageLive(_8); */
    _9 = WaitForSingleObject(_1, _4);
    goto bb4;
bb4:
    _8 = _9;
#line 193 "rt\compat_runtime_windows.w"
    _10 = (_8 == 0);
    if (_10 == 1) {
        goto bb5;
    }
    else {
        goto bb6;
    }
bb5:
#line 194 "rt\compat_runtime_windows.w"
    /* StorageLive(_11); */
    _11 = 0;
#line 195 "rt\compat_runtime_windows.w"
    _12 = (uint32_t*)(&_11);
    _13 = GetExitCodeProcess(_1, _12);
    goto bb8;
bb6:
    goto bb7;
bb7:
#line 199 "rt\compat_runtime_windows.w"
    _17 = (_8 == 258);
    if (_17 == 1) {
        goto bb12;
    }
    else {
        goto bb13;
    }
bb8:
    win32_close__145(_1);
    goto bb9;
bb9:
    win32_close__145(_2);
    goto bb10;
bb10:
#line 198 "rt\compat_runtime_windows.w"
    _16 = ((int32_t)(_11));
    _0 = _16;
    return _0;
bb11:
    goto bb7;
bb12:
#line 200 "rt\compat_runtime_windows.w"
    _18 = ((uint32_t)(124));
    _19 = TerminateProcess(_1, _18);
    goto bb15;
bb13:
    goto bb14;
bb14:
    win32_close__145(_1);
    goto bb20;
bb15:
#line 201 "rt\compat_runtime_windows.w"
    /* StorageLive(_20); */
    _20 = 0;
#line 202 "rt\compat_runtime_windows.w"
    _21 = (uint32_t*)(&_20);
    _22 = GetExitCodeProcess(_1, _21);
    goto bb16;
bb16:
    win32_close__145(_1);
    goto bb17;
bb17:
    win32_close__145(_2);
    goto bb18;
bb18:
#line 205 "rt\compat_runtime_windows.w"
    _0 = 124;
    return _0;
bb19:
    goto bb14;
bb20:
    win32_close__145(_2);
    goto bb21;
bb21:
    _27 = win_last_error__121();
    goto bb22;
bb22:
#line 208 "rt\compat_runtime_windows.w"
    _28 = (-(_27));
    _0 = _28;
    return _0;
bb23:
    _0 = (__typeof__(_0)){0};
    return _0;
bb24: ;
bb25: ;
bb26: ;
bb27: ;
bb28: ;
bb29: ;
bb30: ;
bb31: ;
bb32: ;
bb33: ;
bb34: ;
bb35: ;
bb36: ;
bb37: ;
bb38: ;
bb39: ;
bb40: ;
bb41: ;
bb42: ;
bb43: ;
}

int32_t run_binary_direct__153(uint8_t* _1) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t _2[104] __attribute__((unused)) = {0};
    uint8_t _3 __attribute__((unused)) = {0};
    uint8_t _4[104] __attribute__((unused)) = {0};
    void* _5 __attribute__((unused)) = {0};
    uint8_t** _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    uint32_t _8 __attribute__((unused)) = {0};
    uint8_t _9[24] __attribute__((unused)) = {0};
    uint8_t _10 __attribute__((unused)) = {0};
    uint8_t _11 __attribute__((unused)) = {0};
    uint8_t _12 __attribute__((unused)) = {0};
    uint8_t _13 __attribute__((unused)) = {0};
    uint8_t _14 __attribute__((unused)) = {0};
    uint8_t _15 __attribute__((unused)) = {0};
    uint8_t _16 __attribute__((unused)) = {0};
    uint8_t _17 __attribute__((unused)) = {0};
    uint8_t _18 __attribute__((unused)) = {0};
    uint8_t _19 __attribute__((unused)) = {0};
    uint8_t _20 __attribute__((unused)) = {0};
    uint8_t _21 __attribute__((unused)) = {0};
    uint8_t _22 __attribute__((unused)) = {0};
    uint8_t _23 __attribute__((unused)) = {0};
    uint8_t _24 __attribute__((unused)) = {0};
    uint8_t _25 __attribute__((unused)) = {0};
    uint8_t _26 __attribute__((unused)) = {0};
    uint8_t _27 __attribute__((unused)) = {0};
    uint8_t _28 __attribute__((unused)) = {0};
    uint8_t _29 __attribute__((unused)) = {0};
    uint8_t _30 __attribute__((unused)) = {0};
    uint8_t _31 __attribute__((unused)) = {0};
    uint8_t _32 __attribute__((unused)) = {0};
    uint8_t _33 __attribute__((unused)) = {0};
    uint8_t _34[24] __attribute__((unused)) = {0};
    uint8_t* _35 __attribute__((unused)) = {0};
    int64_t _36 __attribute__((unused)) = {0};
    with_str _37 __attribute__((unused)) = {0};
    uint8_t* _38 __attribute__((unused)) = {0};
    uint8_t* _39 __attribute__((unused)) = {0};
    int64_t _40 __attribute__((unused)) = {0};
    with_str _41 __attribute__((unused)) = {0};
    uint8_t* _42 __attribute__((unused)) = {0};
    int32_t _43 __attribute__((unused)) = {0};
    uint8_t* _44 __attribute__((unused)) = {0};
    uint8_t* _45 __attribute__((unused)) = {0};
    uint8_t* _46 __attribute__((unused)) = {0};
    uint8_t* _47 __attribute__((unused)) = {0};
    void* _48 __attribute__((unused)) = {0};
    uint8_t** _49 __attribute__((unused)) = {0};
    uint8_t* _50 __attribute__((unused)) = {0};
    void* _51 __attribute__((unused)) = {0};
    uint8_t** _52 __attribute__((unused)) = {0};
    uint8_t* _53 __attribute__((unused)) = {0};
    int32_t _54 __attribute__((unused)) = {0};
    bool _55 __attribute__((unused)) = {0};
    int32_t _56 __attribute__((unused)) = {0};
    int32_t _57 __attribute__((unused)) = {0};
    int64_t _58 __attribute__((unused)) = {0};
    void* _59 __attribute__((unused)) = {0};
    int64_t _60 __attribute__((unused)) = {0};
    int64_t _61 __attribute__((unused)) = {0};
    int64_t _62 __attribute__((unused)) = {0};
    void* _63 __attribute__((unused)) = {0};
    int64_t _64 __attribute__((unused)) = {0};
    int64_t _65 __attribute__((unused)) = {0};
    int32_t _66 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 210 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
#line 211 "rt\compat_runtime_windows.w"
    /* StorageLive(_2); */
    _3 = ((uint8_t)(0));
    { __typeof__(_4[0]) __with_fill = _3; for (int64_t __with_i = 0; __with_i < 104; __with_i++) { _4[__with_i] = __with_fill; } }
    memcpy(_2, _4, sizeof(_2));
#line 212 "rt\compat_runtime_windows.w"
    _5 = (&_2);
    _6 = (uint8_t**)((uint8_t**)(_5));
    _7 = (uint8_t*)((uint8_t*)(_6));
    _8 = fill_startupinfo__137(_7, -1, -1, -1);
    goto bb1;
bb1:
#line 213 "rt\compat_runtime_windows.w"
    /* StorageLive(_9); */
    _10 = ((uint8_t)(0));
    _11 = ((uint8_t)(0));
    _12 = ((uint8_t)(0));
    _13 = ((uint8_t)(0));
    _14 = ((uint8_t)(0));
    _15 = ((uint8_t)(0));
    _16 = ((uint8_t)(0));
    _17 = ((uint8_t)(0));
    _18 = ((uint8_t)(0));
    _19 = ((uint8_t)(0));
    _20 = ((uint8_t)(0));
    _21 = ((uint8_t)(0));
    _22 = ((uint8_t)(0));
    _23 = ((uint8_t)(0));
    _24 = ((uint8_t)(0));
    _25 = ((uint8_t)(0));
    _26 = ((uint8_t)(0));
    _27 = ((uint8_t)(0));
    _28 = ((uint8_t)(0));
    _29 = ((uint8_t)(0));
    _30 = ((uint8_t)(0));
    _31 = ((uint8_t)(0));
    _32 = ((uint8_t)(0));
    _33 = ((uint8_t)(0));
    { uint8_t __with_arr_tmp[24] = {_10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33}; memcpy(_34, __with_arr_tmp, sizeof(_34)); }
    memcpy(_9, _34, sizeof(_9));
#line 214 "rt\compat_runtime_windows.w"
    /* StorageLive(_35); */
    _36 = cstr_len__120(_1);
    goto bb2;
bb2:
    _37 = make_str__111(_1, _36);
    goto bb3;
bb3:
    _38 = str_to_c_buf__115(_37);
    goto bb4;
bb4:
    _35 = _38;
#line 215 "rt\compat_runtime_windows.w"
    /* StorageLive(_39); */
    _40 = cstr_len__120(_1);
    goto bb5;
bb5:
    _41 = make_str__111(_1, _40);
    goto bb6;
bb6:
    _42 = str_to_c_buf__115(_41);
    goto bb7;
bb7:
    _39 = _42;
#line 216 "rt\compat_runtime_windows.w"
    /* StorageLive(_43); */
    _44 = (uint8_t*)((uint8_t*)(0));
    _45 = (uint8_t*)((uint8_t*)(0));
    _46 = (uint8_t*)((uint8_t*)(0));
    _47 = (uint8_t*)((uint8_t*)(0));
#line 217 "rt\compat_runtime_windows.w"
    _48 = (&_2);
    _49 = (uint8_t**)((uint8_t**)(_48));
    _50 = (uint8_t*)((uint8_t*)(_49));
    _51 = (&_9);
    _52 = (uint8_t**)((uint8_t**)(_51));
    _53 = (uint8_t*)((uint8_t*)(_52));
    _54 = CreateProcessA(_39, _35, _44, _45, 0, 0, _46, _47, _50, _53);
    goto bb8;
bb8:
#line 216 "rt\compat_runtime_windows.w"
    _43 = _54;
#line 218 "rt\compat_runtime_windows.w"
    _55 = (_43 == 0);
    if (_55 == 1) {
        goto bb9;
    }
    else {
        goto bb10;
    }
bb9:
    _56 = win_last_error__121();
    goto bb12;
bb10:
    goto bb11;
bb11:
#line 220 "rt\compat_runtime_windows.w"
    /* StorageLive(_58); */
    _59 = (&_9);
    _60 = ((int64_t)(_59));
    _61 = load_i64__127(_60, 0);
    goto bb14;
bb12:
#line 219 "rt\compat_runtime_windows.w"
    _57 = (-(_56));
    _0 = _57;
    return _0;
bb13:
    goto bb11;
bb14:
#line 220 "rt\compat_runtime_windows.w"
    _58 = _61;
#line 221 "rt\compat_runtime_windows.w"
    /* StorageLive(_62); */
    _63 = (&_9);
    _64 = ((int64_t)(_63));
    _65 = load_i64__127(_64, 8);
    goto bb15;
bb15:
    _62 = _65;
    _66 = wait_for_process_timeout__147(_58, _62, -1);
    goto bb16;
bb16:
#line 222 "rt\compat_runtime_windows.w"
    _0 = _66;
    return _0;
bb17: ;
bb18: ;
bb19: ;
bb20: ;
bb21: ;
bb22: ;
bb23: ;
bb24: ;
bb25: ;
bb26: ;
bb27: ;
bb28: ;
bb29: ;
bb30: ;
bb31: ;
bb32: ;
bb33: ;
bb34: ;
bb35: ;
bb36: ;
bb37: ;
bb38: ;
bb39: ;
bb40: ;
bb41: ;
bb42: ;
bb43: ;
bb44: ;
bb45: ;
bb46: ;
bb47: ;
bb48: ;
bb49: ;
bb50: ;
bb51: ;
bb52: ;
bb53: ;
bb54: ;
bb55: ;
bb56: ;
bb57: ;
bb58: ;
bb59: ;
bb60: ;
bb61: ;
bb62: ;
bb63: ;
bb64: ;
bb65: ;
bb66: ;
bb67: ;
bb68: ;
bb69: ;
bb70: ;
bb71: ;
bb72: ;
bb73: ;
bb74: ;
bb75: ;
bb76: ;
bb77: ;
bb78: ;
bb79: ;
}

int32_t run_argv_direct_cwd__158(uint8_t* _1, int64_t _2, uint8_t* _3) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _4 __attribute__((unused)) = {0};
    uint8_t* _5 __attribute__((unused)) = {0};
    uint8_t* _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    uint8_t _8[104] __attribute__((unused)) = {0};
    uint8_t _9 __attribute__((unused)) = {0};
    uint8_t _10[104] __attribute__((unused)) = {0};
    void* _11 __attribute__((unused)) = {0};
    uint8_t** _12 __attribute__((unused)) = {0};
    uint8_t* _13 __attribute__((unused)) = {0};
    uint32_t _14 __attribute__((unused)) = {0};
    uint8_t _15[24] __attribute__((unused)) = {0};
    uint8_t _16 __attribute__((unused)) = {0};
    uint8_t _17 __attribute__((unused)) = {0};
    uint8_t _18 __attribute__((unused)) = {0};
    uint8_t _19 __attribute__((unused)) = {0};
    uint8_t _20 __attribute__((unused)) = {0};
    uint8_t _21 __attribute__((unused)) = {0};
    uint8_t _22 __attribute__((unused)) = {0};
    uint8_t _23 __attribute__((unused)) = {0};
    uint8_t _24 __attribute__((unused)) = {0};
    uint8_t _25 __attribute__((unused)) = {0};
    uint8_t _26 __attribute__((unused)) = {0};
    uint8_t _27 __attribute__((unused)) = {0};
    uint8_t _28 __attribute__((unused)) = {0};
    uint8_t _29 __attribute__((unused)) = {0};
    uint8_t _30 __attribute__((unused)) = {0};
    uint8_t _31 __attribute__((unused)) = {0};
    uint8_t _32 __attribute__((unused)) = {0};
    uint8_t _33 __attribute__((unused)) = {0};
    uint8_t _34 __attribute__((unused)) = {0};
    uint8_t _35 __attribute__((unused)) = {0};
    uint8_t _36 __attribute__((unused)) = {0};
    uint8_t _37 __attribute__((unused)) = {0};
    uint8_t _38 __attribute__((unused)) = {0};
    uint8_t _39 __attribute__((unused)) = {0};
    uint8_t _40[24] __attribute__((unused)) = {0};
    int32_t _41 __attribute__((unused)) = {0};
    uint8_t* _42 __attribute__((unused)) = {0};
    uint8_t* _43 __attribute__((unused)) = {0};
    uint8_t* _44 __attribute__((unused)) = {0};
    void* _45 __attribute__((unused)) = {0};
    uint8_t** _46 __attribute__((unused)) = {0};
    uint8_t* _47 __attribute__((unused)) = {0};
    void* _48 __attribute__((unused)) = {0};
    uint8_t** _49 __attribute__((unused)) = {0};
    uint8_t* _50 __attribute__((unused)) = {0};
    int32_t _51 __attribute__((unused)) = {0};
    bool _52 __attribute__((unused)) = {0};
    int32_t _53 __attribute__((unused)) = {0};
    int32_t _54 __attribute__((unused)) = {0};
    int64_t _55 __attribute__((unused)) = {0};
    void* _56 __attribute__((unused)) = {0};
    int64_t _57 __attribute__((unused)) = {0};
    int64_t _58 __attribute__((unused)) = {0};
    int64_t _59 __attribute__((unused)) = {0};
    void* _60 __attribute__((unused)) = {0};
    int64_t _61 __attribute__((unused)) = {0};
    int64_t _62 __attribute__((unused)) = {0};
    int32_t _63 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 224 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
#line 225 "rt\compat_runtime_windows.w"
    /* StorageLive(_4); */
    _5 = first_arg_from_blob__136(_1, _2);
    goto bb1;
bb1:
    _4 = _5;
#line 226 "rt\compat_runtime_windows.w"
    /* StorageLive(_6); */
    _7 = build_command_line_from_blob__130(_1, _2);
    goto bb2;
bb2:
    _6 = _7;
#line 227 "rt\compat_runtime_windows.w"
    /* StorageLive(_8); */
    _9 = ((uint8_t)(0));
    { __typeof__(_10[0]) __with_fill = _9; for (int64_t __with_i = 0; __with_i < 104; __with_i++) { _10[__with_i] = __with_fill; } }
    memcpy(_8, _10, sizeof(_8));
#line 228 "rt\compat_runtime_windows.w"
    _11 = (&_8);
    _12 = (uint8_t**)((uint8_t**)(_11));
    _13 = (uint8_t*)((uint8_t*)(_12));
    _14 = fill_startupinfo__137(_13, -1, -1, -1);
    goto bb3;
bb3:
#line 229 "rt\compat_runtime_windows.w"
    /* StorageLive(_15); */
    _16 = ((uint8_t)(0));
    _17 = ((uint8_t)(0));
    _18 = ((uint8_t)(0));
    _19 = ((uint8_t)(0));
    _20 = ((uint8_t)(0));
    _21 = ((uint8_t)(0));
    _22 = ((uint8_t)(0));
    _23 = ((uint8_t)(0));
    _24 = ((uint8_t)(0));
    _25 = ((uint8_t)(0));
    _26 = ((uint8_t)(0));
    _27 = ((uint8_t)(0));
    _28 = ((uint8_t)(0));
    _29 = ((uint8_t)(0));
    _30 = ((uint8_t)(0));
    _31 = ((uint8_t)(0));
    _32 = ((uint8_t)(0));
    _33 = ((uint8_t)(0));
    _34 = ((uint8_t)(0));
    _35 = ((uint8_t)(0));
    _36 = ((uint8_t)(0));
    _37 = ((uint8_t)(0));
    _38 = ((uint8_t)(0));
    _39 = ((uint8_t)(0));
    { uint8_t __with_arr_tmp[24] = {_16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39}; memcpy(_40, __with_arr_tmp, sizeof(_40)); }
    memcpy(_15, _40, sizeof(_15));
#line 230 "rt\compat_runtime_windows.w"
    /* StorageLive(_41); */
    _42 = (uint8_t*)((uint8_t*)(0));
    _43 = (uint8_t*)((uint8_t*)(0));
    _44 = (uint8_t*)((uint8_t*)(0));
#line 231 "rt\compat_runtime_windows.w"
    _45 = (&_8);
    _46 = (uint8_t**)((uint8_t**)(_45));
    _47 = (uint8_t*)((uint8_t*)(_46));
    _48 = (&_15);
    _49 = (uint8_t**)((uint8_t**)(_48));
    _50 = (uint8_t*)((uint8_t*)(_49));
    _51 = CreateProcessA(_4, _6, _42, _43, 0, 0, _44, _3, _47, _50);
    goto bb4;
bb4:
#line 230 "rt\compat_runtime_windows.w"
    _41 = _51;
#line 232 "rt\compat_runtime_windows.w"
    _52 = (_41 == 0);
    if (_52 == 1) {
        goto bb5;
    }
    else {
        goto bb6;
    }
bb5:
    _53 = win_last_error__121();
    goto bb8;
bb6:
    goto bb7;
bb7:
#line 234 "rt\compat_runtime_windows.w"
    /* StorageLive(_55); */
    _56 = (&_15);
    _57 = ((int64_t)(_56));
    _58 = load_i64__127(_57, 0);
    goto bb10;
bb8:
#line 233 "rt\compat_runtime_windows.w"
    _54 = (-(_53));
    _0 = _54;
    return _0;
bb9:
    goto bb7;
bb10:
#line 234 "rt\compat_runtime_windows.w"
    _55 = _58;
#line 235 "rt\compat_runtime_windows.w"
    /* StorageLive(_59); */
    _60 = (&_15);
    _61 = ((int64_t)(_60));
    _62 = load_i64__127(_61, 8);
    goto bb11;
bb11:
    _59 = _62;
    _63 = wait_for_process_timeout__147(_55, _59, -1);
    goto bb12;
bb12:
#line 236 "rt\compat_runtime_windows.w"
    _0 = _63;
    return _0;
bb13: ;
bb14: ;
bb15: ;
bb16: ;
bb17: ;
bb18: ;
bb19: ;
bb20: ;
bb21: ;
bb22: ;
bb23: ;
bb24: ;
bb25: ;
bb26: ;
bb27: ;
bb28: ;
bb29: ;
bb30: ;
bb31: ;
bb32: ;
bb33: ;
bb34: ;
bb35: ;
bb36: ;
bb37: ;
bb38: ;
bb39: ;
bb40: ;
bb41: ;
bb42: ;
bb43: ;
bb44: ;
bb45: ;
bb46: ;
bb47: ;
bb48: ;
bb49: ;
bb50: ;
bb51: ;
bb52: ;
bb53: ;
bb54: ;
bb55: ;
bb56: ;
bb57: ;
bb58: ;
bb59: ;
bb60: ;
bb61: ;
bb62: ;
bb63: ;
bb64: ;
bb65: ;
bb66: ;
bb67: ;
bb68: ;
bb69: ;
bb70: ;
bb71: ;
bb72: ;
bb73: ;
bb74: ;
bb75: ;
}

int32_t run_argv_direct__161(uint8_t* _1, int64_t _2) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _3 __attribute__((unused)) = {0};
    int32_t _4 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 238 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 239 "rt\compat_runtime_windows.w"
    _3 = (uint8_t*)((uint8_t*)(0));
    _4 = run_argv_direct_cwd__158(_1, _2, _3);
    goto bb1;
bb1:
    _0 = _4;
    return _0;
bb2: ;
bb3: ;
}

int32_t run_argv_capture_cwd__162(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4, int32_t _5, uint8_t* _6, uint8_t* _7) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _8 __attribute__((unused)) = {0};
    uint8_t* _9 __attribute__((unused)) = {0};
    uint8_t* _10 __attribute__((unused)) = {0};
    uint8_t* _11 __attribute__((unused)) = {0};
    int64_t _12 __attribute__((unused)) = {0};
    int64_t _13 __attribute__((unused)) = {0};
    int64_t _14 __attribute__((unused)) = {0};
    int64_t _15 __attribute__((unused)) = {0};
    bool _16 __attribute__((unused)) = {0};
    int64_t _17 __attribute__((unused)) = {0};
    bool _18 __attribute__((unused)) = {0};
    int32_t _19 __attribute__((unused)) = {0};
    int32_t _20 __attribute__((unused)) = {0};
    int64_t _21 __attribute__((unused)) = {0};
    bool _22 __attribute__((unused)) = {0};
    int64_t _23 __attribute__((unused)) = {0};
    bool _24 __attribute__((unused)) = {0};
    int32_t _25 __attribute__((unused)) = {0};
    int32_t _26 __attribute__((unused)) = {0};
    int32_t _27 __attribute__((unused)) = {0};
    int64_t _28 __attribute__((unused)) = {0};
    bool _29 __attribute__((unused)) = {0};
    int64_t _30 __attribute__((unused)) = {0};
    bool _31 __attribute__((unused)) = {0};
    int32_t _32 __attribute__((unused)) = {0};
    int32_t _33 __attribute__((unused)) = {0};
    int32_t _34 __attribute__((unused)) = {0};
    int32_t _35 __attribute__((unused)) = {0};
    uint8_t _36[104] __attribute__((unused)) = {0};
    uint8_t _37 __attribute__((unused)) = {0};
    uint8_t _38[104] __attribute__((unused)) = {0};
    void* _39 __attribute__((unused)) = {0};
    uint8_t** _40 __attribute__((unused)) = {0};
    uint8_t* _41 __attribute__((unused)) = {0};
    uint32_t _42 __attribute__((unused)) = {0};
    uint8_t _43[24] __attribute__((unused)) = {0};
    uint8_t _44 __attribute__((unused)) = {0};
    uint8_t _45 __attribute__((unused)) = {0};
    uint8_t _46 __attribute__((unused)) = {0};
    uint8_t _47 __attribute__((unused)) = {0};
    uint8_t _48 __attribute__((unused)) = {0};
    uint8_t _49 __attribute__((unused)) = {0};
    uint8_t _50 __attribute__((unused)) = {0};
    uint8_t _51 __attribute__((unused)) = {0};
    uint8_t _52 __attribute__((unused)) = {0};
    uint8_t _53 __attribute__((unused)) = {0};
    uint8_t _54 __attribute__((unused)) = {0};
    uint8_t _55 __attribute__((unused)) = {0};
    uint8_t _56 __attribute__((unused)) = {0};
    uint8_t _57 __attribute__((unused)) = {0};
    uint8_t _58 __attribute__((unused)) = {0};
    uint8_t _59 __attribute__((unused)) = {0};
    uint8_t _60 __attribute__((unused)) = {0};
    uint8_t _61 __attribute__((unused)) = {0};
    uint8_t _62 __attribute__((unused)) = {0};
    uint8_t _63 __attribute__((unused)) = {0};
    uint8_t _64 __attribute__((unused)) = {0};
    uint8_t _65 __attribute__((unused)) = {0};
    uint8_t _66 __attribute__((unused)) = {0};
    uint8_t _67 __attribute__((unused)) = {0};
    uint8_t _68[24] __attribute__((unused)) = {0};
    int32_t _69 __attribute__((unused)) = {0};
    uint8_t* _70 __attribute__((unused)) = {0};
    uint8_t* _71 __attribute__((unused)) = {0};
    uint8_t* _72 __attribute__((unused)) = {0};
    void* _73 __attribute__((unused)) = {0};
    uint8_t** _74 __attribute__((unused)) = {0};
    uint8_t* _75 __attribute__((unused)) = {0};
    void* _76 __attribute__((unused)) = {0};
    uint8_t** _77 __attribute__((unused)) = {0};
    uint8_t* _78 __attribute__((unused)) = {0};
    int32_t _79 __attribute__((unused)) = {0};
    bool _80 __attribute__((unused)) = {0};
    int32_t _81 __attribute__((unused)) = {0};
    int32_t _82 __attribute__((unused)) = {0};
    int32_t _83 __attribute__((unused)) = {0};
    int32_t _84 __attribute__((unused)) = {0};
    int32_t _85 __attribute__((unused)) = {0};
    int64_t _86 __attribute__((unused)) = {0};
    void* _87 __attribute__((unused)) = {0};
    int64_t _88 __attribute__((unused)) = {0};
    int64_t _89 __attribute__((unused)) = {0};
    int64_t _90 __attribute__((unused)) = {0};
    void* _91 __attribute__((unused)) = {0};
    int64_t _92 __attribute__((unused)) = {0};
    int64_t _93 __attribute__((unused)) = {0};
    int32_t _94 __attribute__((unused)) = {0};
    int32_t _95 __attribute__((unused)) = {0};
    int32_t _96 __attribute__((unused)) = {0};
    int32_t _97 __attribute__((unused)) = {0};
    int32_t _98 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 241 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
    /* StorageLive(_5); */
    /* StorageLive(_6); */
    /* StorageLive(_7); */
#line 242 "rt\compat_runtime_windows.w"
    /* StorageLive(_8); */
    _9 = first_arg_from_blob__136(_1, _2);
    goto bb1;
bb1:
    _8 = _9;
#line 243 "rt\compat_runtime_windows.w"
    /* StorageLive(_10); */
    _11 = build_command_line_from_blob__130(_1, _2);
    goto bb2;
bb2:
    _10 = _11;
#line 244 "rt\compat_runtime_windows.w"
    /* StorageLive(_12); */
    _12 = -1;
#line 245 "rt\compat_runtime_windows.w"
    /* StorageLive(_13); */
    _13 = -1;
#line 246 "rt\compat_runtime_windows.w"
    /* StorageLive(_14); */
    _14 = -1;
#line 247 "rt\compat_runtime_windows.w"
    _15 = ((int64_t)(_3));
    _16 = (_15 != 0);
    if (_16 == 1) {
        goto bb3;
    }
    else {
        goto bb4;
    }
bb3:
    _17 = create_file_for_redirect__142(_3, 1);
    goto bb6;
bb4:
    goto bb5;
bb5:
#line 251 "rt\compat_runtime_windows.w"
    _21 = ((int64_t)(_4));
    _22 = (_21 != 0);
    if (_22 == 1) {
        goto bb12;
    }
    else {
        goto bb13;
    }
bb6:
#line 248 "rt\compat_runtime_windows.w"
    _12 = _17;
#line 249 "rt\compat_runtime_windows.w"
    _18 = (_12 == -1);
    if (_18 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    _19 = win_last_error__121();
    goto bb10;
bb8:
    goto bb9;
bb9:
    goto bb5;
bb10:
#line 250 "rt\compat_runtime_windows.w"
    _20 = (-(_19));
    _0 = _20;
    return _0;
bb11:
    goto bb9;
bb12:
    _23 = create_file_for_redirect__142(_4, 1);
    goto bb15;
bb13:
    goto bb14;
bb14:
#line 256 "rt\compat_runtime_windows.w"
    _28 = ((int64_t)(_6));
    _29 = (_28 != 0);
    if (_29 == 1) {
        goto bb22;
    }
    else {
        goto bb23;
    }
bb15:
#line 252 "rt\compat_runtime_windows.w"
    _13 = _23;
#line 253 "rt\compat_runtime_windows.w"
    _24 = (_13 == -1);
    if (_24 == 1) {
        goto bb16;
    }
    else {
        goto bb17;
    }
bb16:
    win32_close__145(_12);
    goto bb19;
bb17:
    goto bb18;
bb18:
    goto bb14;
bb19:
    _26 = win_last_error__121();
    goto bb20;
bb20:
#line 255 "rt\compat_runtime_windows.w"
    _27 = (-(_26));
    _0 = _27;
    return _0;
bb21:
    goto bb18;
bb22:
    _30 = create_file_for_redirect__142(_6, 0);
    goto bb25;
bb23:
    goto bb24;
bb24:
#line 263 "rt\compat_runtime_windows.w"
    /* StorageLive(_36); */
    _37 = ((uint8_t)(0));
    { __typeof__(_38[0]) __with_fill = _37; for (int64_t __with_i = 0; __with_i < 104; __with_i++) { _38[__with_i] = __with_fill; } }
    memcpy(_36, _38, sizeof(_36));
#line 264 "rt\compat_runtime_windows.w"
    _39 = (&_36);
    _40 = (uint8_t**)((uint8_t**)(_39));
    _41 = (uint8_t*)((uint8_t*)(_40));
    _42 = fill_startupinfo__137(_41, _14, _12, _13);
    goto bb33;
bb25:
#line 257 "rt\compat_runtime_windows.w"
    _14 = _30;
#line 258 "rt\compat_runtime_windows.w"
    _31 = (_14 == -1);
    if (_31 == 1) {
        goto bb26;
    }
    else {
        goto bb27;
    }
bb26:
    win32_close__145(_12);
    goto bb29;
bb27:
    goto bb28;
bb28:
    goto bb24;
bb29:
    win32_close__145(_13);
    goto bb30;
bb30:
    _34 = win_last_error__121();
    goto bb31;
bb31:
#line 261 "rt\compat_runtime_windows.w"
    _35 = (-(_34));
    _0 = _35;
    return _0;
bb32:
    goto bb28;
bb33:
#line 265 "rt\compat_runtime_windows.w"
    /* StorageLive(_43); */
    _44 = ((uint8_t)(0));
    _45 = ((uint8_t)(0));
    _46 = ((uint8_t)(0));
    _47 = ((uint8_t)(0));
    _48 = ((uint8_t)(0));
    _49 = ((uint8_t)(0));
    _50 = ((uint8_t)(0));
    _51 = ((uint8_t)(0));
    _52 = ((uint8_t)(0));
    _53 = ((uint8_t)(0));
    _54 = ((uint8_t)(0));
    _55 = ((uint8_t)(0));
    _56 = ((uint8_t)(0));
    _57 = ((uint8_t)(0));
    _58 = ((uint8_t)(0));
    _59 = ((uint8_t)(0));
    _60 = ((uint8_t)(0));
    _61 = ((uint8_t)(0));
    _62 = ((uint8_t)(0));
    _63 = ((uint8_t)(0));
    _64 = ((uint8_t)(0));
    _65 = ((uint8_t)(0));
    _66 = ((uint8_t)(0));
    _67 = ((uint8_t)(0));
    { uint8_t __with_arr_tmp[24] = {_44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67}; memcpy(_68, __with_arr_tmp, sizeof(_68)); }
    memcpy(_43, _68, sizeof(_43));
#line 266 "rt\compat_runtime_windows.w"
    /* StorageLive(_69); */
    _70 = (uint8_t*)((uint8_t*)(0));
    _71 = (uint8_t*)((uint8_t*)(0));
    _72 = (uint8_t*)((uint8_t*)(0));
#line 267 "rt\compat_runtime_windows.w"
    _73 = (&_36);
    _74 = (uint8_t**)((uint8_t**)(_73));
    _75 = (uint8_t*)((uint8_t*)(_74));
    _76 = (&_43);
    _77 = (uint8_t**)((uint8_t**)(_76));
    _78 = (uint8_t*)((uint8_t*)(_77));
    _79 = CreateProcessA(_8, _10, _70, _71, 1, 0, _72, _7, _75, _78);
    goto bb34;
bb34:
#line 266 "rt\compat_runtime_windows.w"
    _69 = _79;
#line 268 "rt\compat_runtime_windows.w"
    _80 = (_69 == 0);
    if (_80 == 1) {
        goto bb35;
    }
    else {
        goto bb36;
    }
bb35:
    win32_close__145(_12);
    goto bb38;
bb36:
    goto bb37;
bb37:
#line 273 "rt\compat_runtime_windows.w"
    /* StorageLive(_86); */
    _87 = (&_43);
    _88 = ((int64_t)(_87));
    _89 = load_i64__127(_88, 0);
    goto bb43;
bb38:
    win32_close__145(_13);
    goto bb39;
bb39:
    win32_close__145(_14);
    goto bb40;
bb40:
    _84 = win_last_error__121();
    goto bb41;
bb41:
#line 272 "rt\compat_runtime_windows.w"
    _85 = (-(_84));
    _0 = _85;
    return _0;
bb42:
    goto bb37;
bb43:
#line 273 "rt\compat_runtime_windows.w"
    _86 = _89;
#line 274 "rt\compat_runtime_windows.w"
    /* StorageLive(_90); */
    _91 = (&_43);
    _92 = ((int64_t)(_91));
    _93 = load_i64__127(_92, 8);
    goto bb44;
bb44:
    _90 = _93;
#line 275 "rt\compat_runtime_windows.w"
    /* StorageLive(_94); */
    _95 = wait_for_process_timeout__147(_86, _90, _5);
    goto bb45;
bb45:
    _94 = _95;
    win32_close__145(_12);
    goto bb46;
bb46:
    win32_close__145(_13);
    goto bb47;
bb47:
    win32_close__145(_14);
    goto bb48;
bb48:
#line 279 "rt\compat_runtime_windows.w"
    _0 = _94;
    return _0;
bb49: ;
bb50: ;
bb51: ;
bb52: ;
bb53: ;
bb54: ;
bb55: ;
bb56: ;
bb57: ;
bb58: ;
bb59: ;
bb60: ;
bb61: ;
bb62: ;
bb63: ;
bb64: ;
bb65: ;
bb66: ;
bb67: ;
bb68: ;
bb69: ;
bb70: ;
bb71: ;
bb72: ;
bb73: ;
bb74: ;
bb75: ;
bb76: ;
bb77: ;
bb78: ;
bb79: ;
bb80: ;
bb81: ;
bb82: ;
bb83: ;
bb84: ;
bb85: ;
bb86: ;
bb87: ;
bb88: ;
bb89: ;
bb90: ;
bb91: ;
bb92: ;
bb93: ;
bb94: ;
bb95: ;
bb96: ;
bb97: ;
bb98: ;
bb99: ;
bb100: ;
bb101: ;
bb102: ;
bb103: ;
bb104: ;
bb105: ;
bb106: ;
bb107: ;
bb108: ;
bb109: ;
bb110: ;
bb111: ;
bb112: ;
bb113: ;
bb114: ;
bb115: ;
bb116: ;
bb117: ;
bb118: ;
bb119: ;
bb120: ;
bb121: ;
bb122: ;
bb123: ;
bb124: ;
bb125: ;
bb126: ;
bb127: ;
bb128: ;
bb129: ;
bb130: ;
bb131: ;
bb132: ;
bb133: ;
bb134: ;
}

int32_t spawn_argv_capture__169(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _5 __attribute__((unused)) = {0};
    uint8_t* _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    uint8_t* _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    int64_t _10 __attribute__((unused)) = {0};
    int64_t _11 __attribute__((unused)) = {0};
    bool _12 __attribute__((unused)) = {0};
    int64_t _13 __attribute__((unused)) = {0};
    bool _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    int32_t _16 __attribute__((unused)) = {0};
    int64_t _17 __attribute__((unused)) = {0};
    bool _18 __attribute__((unused)) = {0};
    int64_t _19 __attribute__((unused)) = {0};
    bool _20 __attribute__((unused)) = {0};
    int32_t _21 __attribute__((unused)) = {0};
    int32_t _22 __attribute__((unused)) = {0};
    int32_t _23 __attribute__((unused)) = {0};
    uint8_t _24[104] __attribute__((unused)) = {0};
    uint8_t _25 __attribute__((unused)) = {0};
    uint8_t _26[104] __attribute__((unused)) = {0};
    void* _27 __attribute__((unused)) = {0};
    uint8_t** _28 __attribute__((unused)) = {0};
    uint8_t* _29 __attribute__((unused)) = {0};
    uint32_t _30 __attribute__((unused)) = {0};
    uint8_t _31[24] __attribute__((unused)) = {0};
    uint8_t _32 __attribute__((unused)) = {0};
    uint8_t _33 __attribute__((unused)) = {0};
    uint8_t _34 __attribute__((unused)) = {0};
    uint8_t _35 __attribute__((unused)) = {0};
    uint8_t _36 __attribute__((unused)) = {0};
    uint8_t _37 __attribute__((unused)) = {0};
    uint8_t _38 __attribute__((unused)) = {0};
    uint8_t _39 __attribute__((unused)) = {0};
    uint8_t _40 __attribute__((unused)) = {0};
    uint8_t _41 __attribute__((unused)) = {0};
    uint8_t _42 __attribute__((unused)) = {0};
    uint8_t _43 __attribute__((unused)) = {0};
    uint8_t _44 __attribute__((unused)) = {0};
    uint8_t _45 __attribute__((unused)) = {0};
    uint8_t _46 __attribute__((unused)) = {0};
    uint8_t _47 __attribute__((unused)) = {0};
    uint8_t _48 __attribute__((unused)) = {0};
    uint8_t _49 __attribute__((unused)) = {0};
    uint8_t _50 __attribute__((unused)) = {0};
    uint8_t _51 __attribute__((unused)) = {0};
    uint8_t _52 __attribute__((unused)) = {0};
    uint8_t _53 __attribute__((unused)) = {0};
    uint8_t _54 __attribute__((unused)) = {0};
    uint8_t _55 __attribute__((unused)) = {0};
    uint8_t _56[24] __attribute__((unused)) = {0};
    int32_t _57 __attribute__((unused)) = {0};
    uint8_t* _58 __attribute__((unused)) = {0};
    uint8_t* _59 __attribute__((unused)) = {0};
    uint8_t* _60 __attribute__((unused)) = {0};
    uint8_t* _61 __attribute__((unused)) = {0};
    void* _62 __attribute__((unused)) = {0};
    uint8_t** _63 __attribute__((unused)) = {0};
    uint8_t* _64 __attribute__((unused)) = {0};
    void* _65 __attribute__((unused)) = {0};
    uint8_t** _66 __attribute__((unused)) = {0};
    uint8_t* _67 __attribute__((unused)) = {0};
    int32_t _68 __attribute__((unused)) = {0};
    bool _69 __attribute__((unused)) = {0};
    int32_t _70 __attribute__((unused)) = {0};
    int32_t _71 __attribute__((unused)) = {0};
    int32_t _72 __attribute__((unused)) = {0};
    int32_t _73 __attribute__((unused)) = {0};
    int64_t _74 __attribute__((unused)) = {0};
    void* _75 __attribute__((unused)) = {0};
    int64_t _76 __attribute__((unused)) = {0};
    int64_t _77 __attribute__((unused)) = {0};
    int64_t _78 __attribute__((unused)) = {0};
    void* _79 __attribute__((unused)) = {0};
    int64_t _80 __attribute__((unused)) = {0};
    int64_t _81 __attribute__((unused)) = {0};
    int32_t _82 __attribute__((unused)) = {0};
    int32_t _83 __attribute__((unused)) = {0};
    void* _84 __attribute__((unused)) = {0};
    int64_t _85 __attribute__((unused)) = {0};
    uint32_t _86 __attribute__((unused)) = {0};
    int32_t _87 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 281 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
#line 282 "rt\compat_runtime_windows.w"
    /* StorageLive(_5); */
    _6 = first_arg_from_blob__136(_1, _2);
    goto bb1;
bb1:
    _5 = _6;
#line 283 "rt\compat_runtime_windows.w"
    /* StorageLive(_7); */
    _8 = build_command_line_from_blob__130(_1, _2);
    goto bb2;
bb2:
    _7 = _8;
#line 284 "rt\compat_runtime_windows.w"
    /* StorageLive(_9); */
    _9 = -1;
#line 285 "rt\compat_runtime_windows.w"
    /* StorageLive(_10); */
    _10 = -1;
#line 286 "rt\compat_runtime_windows.w"
    _11 = ((int64_t)(_3));
    _12 = (_11 != 0);
    if (_12 == 1) {
        goto bb3;
    }
    else {
        goto bb4;
    }
bb3:
    _13 = create_file_for_redirect__142(_3, 1);
    goto bb6;
bb4:
    goto bb5;
bb5:
#line 290 "rt\compat_runtime_windows.w"
    _17 = ((int64_t)(_4));
    _18 = (_17 != 0);
    if (_18 == 1) {
        goto bb12;
    }
    else {
        goto bb13;
    }
bb6:
#line 287 "rt\compat_runtime_windows.w"
    _9 = _13;
#line 288 "rt\compat_runtime_windows.w"
    _14 = (_9 == -1);
    if (_14 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    _15 = win_last_error__121();
    goto bb10;
bb8:
    goto bb9;
bb9:
    goto bb5;
bb10:
#line 289 "rt\compat_runtime_windows.w"
    _16 = (-(_15));
    _0 = _16;
    return _0;
bb11:
    goto bb9;
bb12:
    _19 = create_file_for_redirect__142(_4, 1);
    goto bb15;
bb13:
    goto bb14;
bb14:
#line 296 "rt\compat_runtime_windows.w"
    /* StorageLive(_24); */
    _25 = ((uint8_t)(0));
    { __typeof__(_26[0]) __with_fill = _25; for (int64_t __with_i = 0; __with_i < 104; __with_i++) { _26[__with_i] = __with_fill; } }
    memcpy(_24, _26, sizeof(_24));
#line 297 "rt\compat_runtime_windows.w"
    _27 = (&_24);
    _28 = (uint8_t**)((uint8_t**)(_27));
    _29 = (uint8_t*)((uint8_t*)(_28));
    _30 = fill_startupinfo__137(_29, -1, _9, _10);
    goto bb22;
bb15:
#line 291 "rt\compat_runtime_windows.w"
    _10 = _19;
#line 292 "rt\compat_runtime_windows.w"
    _20 = (_10 == -1);
    if (_20 == 1) {
        goto bb16;
    }
    else {
        goto bb17;
    }
bb16:
    win32_close__145(_9);
    goto bb19;
bb17:
    goto bb18;
bb18:
    goto bb14;
bb19:
    _22 = win_last_error__121();
    goto bb20;
bb20:
#line 294 "rt\compat_runtime_windows.w"
    _23 = (-(_22));
    _0 = _23;
    return _0;
bb21:
    goto bb18;
bb22:
#line 298 "rt\compat_runtime_windows.w"
    /* StorageLive(_31); */
    _32 = ((uint8_t)(0));
    _33 = ((uint8_t)(0));
    _34 = ((uint8_t)(0));
    _35 = ((uint8_t)(0));
    _36 = ((uint8_t)(0));
    _37 = ((uint8_t)(0));
    _38 = ((uint8_t)(0));
    _39 = ((uint8_t)(0));
    _40 = ((uint8_t)(0));
    _41 = ((uint8_t)(0));
    _42 = ((uint8_t)(0));
    _43 = ((uint8_t)(0));
    _44 = ((uint8_t)(0));
    _45 = ((uint8_t)(0));
    _46 = ((uint8_t)(0));
    _47 = ((uint8_t)(0));
    _48 = ((uint8_t)(0));
    _49 = ((uint8_t)(0));
    _50 = ((uint8_t)(0));
    _51 = ((uint8_t)(0));
    _52 = ((uint8_t)(0));
    _53 = ((uint8_t)(0));
    _54 = ((uint8_t)(0));
    _55 = ((uint8_t)(0));
    { uint8_t __with_arr_tmp[24] = {_32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55}; memcpy(_56, __with_arr_tmp, sizeof(_56)); }
    memcpy(_31, _56, sizeof(_31));
#line 299 "rt\compat_runtime_windows.w"
    /* StorageLive(_57); */
    _58 = (uint8_t*)((uint8_t*)(0));
    _59 = (uint8_t*)((uint8_t*)(0));
    _60 = (uint8_t*)((uint8_t*)(0));
    _61 = (uint8_t*)((uint8_t*)(0));
#line 300 "rt\compat_runtime_windows.w"
    _62 = (&_24);
    _63 = (uint8_t**)((uint8_t**)(_62));
    _64 = (uint8_t*)((uint8_t*)(_63));
    _65 = (&_31);
    _66 = (uint8_t**)((uint8_t**)(_65));
    _67 = (uint8_t*)((uint8_t*)(_66));
    _68 = CreateProcessA(_5, _7, _58, _59, 1, 512, _60, _61, _64, _67);
    goto bb23;
bb23:
#line 299 "rt\compat_runtime_windows.w"
    _57 = _68;
#line 301 "rt\compat_runtime_windows.w"
    _69 = (_57 == 0);
    if (_69 == 1) {
        goto bb24;
    }
    else {
        goto bb25;
    }
bb24:
    win32_close__145(_9);
    goto bb27;
bb25:
    goto bb26;
bb26:
#line 305 "rt\compat_runtime_windows.w"
    /* StorageLive(_74); */
    _75 = (&_31);
    _76 = ((int64_t)(_75));
    _77 = load_i64__127(_76, 0);
    goto bb31;
bb27:
    win32_close__145(_10);
    goto bb28;
bb28:
    _72 = win_last_error__121();
    goto bb29;
bb29:
#line 304 "rt\compat_runtime_windows.w"
    _73 = (-(_72));
    _0 = _73;
    return _0;
bb30:
    goto bb26;
bb31:
#line 305 "rt\compat_runtime_windows.w"
    _74 = _77;
#line 306 "rt\compat_runtime_windows.w"
    /* StorageLive(_78); */
    _79 = (&_31);
    _80 = ((int64_t)(_79));
    _81 = load_i64__127(_80, 8);
    goto bb32;
bb32:
    _78 = _81;
    win32_close__145(_78);
    goto bb33;
bb33:
#line 310 "rt\compat_runtime_windows.w"
    /* StorageLive(_83); */
    _84 = (&_31);
    _85 = ((int64_t)(_84));
    _86 = load_u32__126(_85, 16);
    goto bb34;
bb34:
    _87 = ((int32_t)(_86));
    _83 = _87;
#line 317 "rt\compat_runtime_windows.w"
    __with_global_last_spawned_handle__109 = _74;
#line 318 "rt\compat_runtime_windows.w"
    _0 = _83;
    return _0;
bb35: ;
bb36: ;
bb37: ;
bb38: ;
bb39: ;
bb40: ;
bb41: ;
bb42: ;
bb43: ;
bb44: ;
bb45: ;
bb46: ;
bb47: ;
bb48: ;
bb49: ;
bb50: ;
bb51: ;
bb52: ;
bb53: ;
bb54: ;
bb55: ;
bb56: ;
bb57: ;
bb58: ;
bb59: ;
bb60: ;
bb61: ;
bb62: ;
bb63: ;
bb64: ;
bb65: ;
bb66: ;
bb67: ;
bb68: ;
bb69: ;
bb70: ;
bb71: ;
bb72: ;
bb73: ;
bb74: ;
bb75: ;
bb76: ;
bb77: ;
bb78: ;
bb79: ;
bb80: ;
bb81: ;
bb82: ;
bb83: ;
bb84: ;
bb85: ;
bb86: ;
bb87: ;
bb88: ;
bb89: ;
bb90: ;
bb91: ;
bb92: ;
bb93: ;
bb94: ;
bb95: ;
bb96: ;
bb97: ;
bb98: ;
bb99: ;
bb100: ;
bb101: ;
bb102: ;
bb103: ;
bb104: ;
bb105: ;
bb106: ;
bb107: ;
bb108: ;
bb109: ;
bb110: ;
bb111: ;
}

int32_t run_argv_capture__171(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4, int32_t _5) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 320 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
    /* StorageLive(_5); */
#line 321 "rt\compat_runtime_windows.w"
    _6 = (uint8_t*)((uint8_t*)(0));
    _7 = (uint8_t*)((uint8_t*)(0));
    _8 = run_argv_capture_cwd__162(_1, _2, _3, _4, _5, _6, _7);
    goto bb1;
bb1:
    _0 = _8;
    return _0;
bb2: ;
bb3: ;
bb4: ;
bb5: ;
bb6: ;
bb7: ;
}

int32_t run_argv_capture_input__172(uint8_t* _1, int64_t _2, uint8_t* _3, uint8_t* _4, int32_t _5, uint8_t* _6) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 323 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
    /* StorageLive(_5); */
    /* StorageLive(_6); */
#line 324 "rt\compat_runtime_windows.w"
    _7 = (uint8_t*)((uint8_t*)(0));
    _8 = run_argv_capture_cwd__162(_1, _2, _3, _4, _5, _6, _7);
    goto bb1;
bb1:
    _0 = _8;
    return _0;
bb2: ;
bb3: ;
bb4: ;
bb5: ;
bb6: ;
bb7: ;
}

int32_t with_setenv_str(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _3 __attribute__((unused)) = {0};
    uint8_t* _4 __attribute__((unused)) = {0};
    int64_t _5 __attribute__((unused)) = {0};
    bool _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    uint8_t* _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    bool _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    int32_t _12 __attribute__((unused)) = {0};
    uint8_t* _13 __attribute__((unused)) = {0};
    uint8_t* _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    int32_t _16 __attribute__((unused)) = {0};
    int32_t _17 __attribute__((unused)) = {0};
    bool _18 __attribute__((unused)) = {0};
    int32_t _19 __attribute__((unused)) = {0};
    int32_t _20 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 329 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 330 "rt\compat_runtime_windows.w"
    /* StorageLive(_3); */
    _4 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _3 = _4;
#line 331 "rt\compat_runtime_windows.w"
    _5 = ((int64_t)(_3));
    _6 = (_5 == 0);
    if (_6 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 332 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 333 "rt\compat_runtime_windows.w"
    /* StorageLive(_7); */
    _8 = str_to_c_buf__115(_2);
    goto bb6;
bb5:
    goto bb4;
bb6:
    _7 = _8;
#line 334 "rt\compat_runtime_windows.w"
    _9 = ((int64_t)(_7));
    _10 = (_9 == 0);
    if (_10 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    with_free(_3);
    goto bb10;
bb8:
    goto bb9;
bb9:
#line 337 "rt\compat_runtime_windows.w"
    /* StorageLive(_12); */
    _13 = (uint8_t*)((uint8_t*)(_3));
    _14 = (uint8_t*)((uint8_t*)(_7));
    _15 = SetEnvironmentVariableA(_13, _14);
    goto bb12;
bb10:
#line 336 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb11:
    goto bb9;
bb12:
#line 337 "rt\compat_runtime_windows.w"
    _12 = _15;
    with_free(_3);
    goto bb13;
bb13:
    with_free(_7);
    goto bb14;
bb14:
#line 340 "rt\compat_runtime_windows.w"
    _18 = (_12 == 0);
    if (_18 == 1) {
        goto bb15;
    }
    else {
        goto bb16;
    }
bb15:
    _19 = win_last_error__121();
    goto bb18;
bb16:
    goto bb17;
bb17:
#line 342 "rt\compat_runtime_windows.w"
    _0 = 0;
    return _0;
bb18:
#line 341 "rt\compat_runtime_windows.w"
    _20 = (-(_19));
    _0 = _20;
    return _0;
bb19:
    goto bb17;
bb20: ;
bb21: ;
bb22: ;
bb23: ;
bb24: ;
bb25: ;
bb26: ;
bb27: ;
bb28: ;
}

void with_install_interrupt_handlers() {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _1 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 348 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    _1 = 0;
    return;
}

void with_raise_stack_limit() {
    int32_t _0 __attribute__((unused)) = {0};
    int32_t _1 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 354 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    _1 = 0;
    return;
}

int32_t with_interrupt_requested() {
    int32_t _0 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 358 "rt\compat_runtime_windows.w"
    _0 = __with_global_interrupt_flag__108;
    return _0;
}

int32_t with_exec_binary(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _2 __attribute__((unused)) = {0};
    uint8_t* _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    bool _5 __attribute__((unused)) = {0};
    bool _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    uint8_t* _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    int32_t _12 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 361 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
#line 362 "rt\compat_runtime_windows.w"
    /* StorageLive(_2); */
    _3 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _2 = _3;
#line 363 "rt\compat_runtime_windows.w"
    _4 = ((int64_t)(_2));
    _5 = (_4 == 0);
    if (_5 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 364 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 365 "rt\compat_runtime_windows.w"
    _7 = (__with_global_interrupt_flag__108 != 0);
    if (_7 == 1) {
        goto bb6;
    }
    else {
        goto bb7;
    }
bb5:
    goto bb4;
bb6:
    with_free(_2);
    goto bb9;
bb7:
    goto bb8;
bb8:
#line 368 "rt\compat_runtime_windows.w"
    /* StorageLive(_9); */
    _10 = (uint8_t*)((uint8_t*)(_2));
    _11 = run_binary_direct__153(_10);
    goto bb11;
bb9:
#line 367 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb10:
    goto bb8;
bb11:
#line 368 "rt\compat_runtime_windows.w"
    _9 = _11;
    with_free(_2);
    goto bb12;
bb12:
#line 370 "rt\compat_runtime_windows.w"
    _0 = _9;
    return _0;
bb13: ;
bb14: ;
bb15: ;
bb16: ;
bb17: ;
}

int32_t with_exec_argv(with_str _1) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _2 __attribute__((unused)) = {0};
    uint8_t* _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    bool _5 __attribute__((unused)) = {0};
    bool _7 __attribute__((unused)) = {0};
    int32_t _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    uint8_t* _10 __attribute__((unused)) = {0};
    int64_t _11 __attribute__((unused)) = {0};
    int32_t _12 __attribute__((unused)) = {0};
    int32_t _13 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 373 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
#line 374 "rt\compat_runtime_windows.w"
    /* StorageLive(_2); */
    _3 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _2 = _3;
#line 375 "rt\compat_runtime_windows.w"
    _4 = ((int64_t)(_2));
    _5 = (_4 == 0);
    if (_5 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 376 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 377 "rt\compat_runtime_windows.w"
    _7 = (__with_global_interrupt_flag__108 != 0);
    if (_7 == 1) {
        goto bb6;
    }
    else {
        goto bb7;
    }
bb5:
    goto bb4;
bb6:
    with_free(_2);
    goto bb9;
bb7:
    goto bb8;
bb8:
#line 380 "rt\compat_runtime_windows.w"
    /* StorageLive(_9); */
    _10 = (uint8_t*)((uint8_t*)(_2));
    _11 = ((_1).len);
    goto bb11;
bb9:
#line 379 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb10:
    goto bb8;
bb11:
    _12 = run_argv_direct__161(_10, _11);
    goto bb12;
bb12:
#line 380 "rt\compat_runtime_windows.w"
    _9 = _12;
    with_free(_2);
    goto bb13;
bb13:
#line 382 "rt\compat_runtime_windows.w"
    _0 = _9;
    return _0;
bb14: ;
bb15: ;
bb16: ;
bb17: ;
bb18: ;
bb19: ;
}

int32_t with_exec_argv_cwd(with_str _1, with_str _2) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _3 __attribute__((unused)) = {0};
    uint8_t* _4 __attribute__((unused)) = {0};
    int64_t _5 __attribute__((unused)) = {0};
    bool _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    uint8_t* _8 __attribute__((unused)) = {0};
    int64_t _9 __attribute__((unused)) = {0};
    bool _10 __attribute__((unused)) = {0};
    int32_t _11 __attribute__((unused)) = {0};
    bool _13 __attribute__((unused)) = {0};
    int32_t _14 __attribute__((unused)) = {0};
    int32_t _15 __attribute__((unused)) = {0};
    int32_t _16 __attribute__((unused)) = {0};
    uint8_t* _17 __attribute__((unused)) = {0};
    int64_t _18 __attribute__((unused)) = {0};
    uint8_t* _19 __attribute__((unused)) = {0};
    int32_t _20 __attribute__((unused)) = {0};
    int32_t _21 __attribute__((unused)) = {0};
    int32_t _22 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 385 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 386 "rt\compat_runtime_windows.w"
    /* StorageLive(_3); */
    _4 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _3 = _4;
#line 387 "rt\compat_runtime_windows.w"
    _5 = ((int64_t)(_3));
    _6 = (_5 == 0);
    if (_6 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 388 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 389 "rt\compat_runtime_windows.w"
    /* StorageLive(_7); */
    _8 = str_to_c_buf__115(_2);
    goto bb6;
bb5:
    goto bb4;
bb6:
    _7 = _8;
#line 390 "rt\compat_runtime_windows.w"
    _9 = ((int64_t)(_7));
    _10 = (_9 == 0);
    if (_10 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    with_free(_3);
    goto bb10;
bb8:
    goto bb9;
bb9:
#line 393 "rt\compat_runtime_windows.w"
    _13 = (__with_global_interrupt_flag__108 != 0);
    if (_13 == 1) {
        goto bb12;
    }
    else {
        goto bb13;
    }
bb10:
#line 392 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb11:
    goto bb9;
bb12:
    with_free(_3);
    goto bb15;
bb13:
    goto bb14;
bb14:
#line 397 "rt\compat_runtime_windows.w"
    /* StorageLive(_16); */
    _17 = (uint8_t*)((uint8_t*)(_3));
    _18 = ((_1).len);
    goto bb18;
bb15:
    with_free(_7);
    goto bb16;
bb16:
#line 396 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb17:
    goto bb14;
bb18:
#line 397 "rt\compat_runtime_windows.w"
    _19 = (uint8_t*)((uint8_t*)(_7));
    _20 = run_argv_direct_cwd__158(_17, _18, _19);
    goto bb19;
bb19:
    _16 = _20;
    with_free(_3);
    goto bb20;
bb20:
    with_free(_7);
    goto bb21;
bb21:
#line 400 "rt\compat_runtime_windows.w"
    _0 = _16;
    return _0;
bb22: ;
bb23: ;
bb24: ;
bb25: ;
bb26: ;
bb27: ;
bb28: ;
bb29: ;
bb30: ;
bb31: ;
bb32: ;
bb33: ;
bb34: ;
}

int32_t with_exec_argv_capture(with_str _1, with_str _2, with_str _3, int32_t _4) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _5 __attribute__((unused)) = {0};
    uint8_t* _6 __attribute__((unused)) = {0};
    int64_t _7 __attribute__((unused)) = {0};
    bool _8 __attribute__((unused)) = {0};
    uint8_t* _9 __attribute__((unused)) = {0};
    uint8_t* _10 __attribute__((unused)) = {0};
    int64_t _11 __attribute__((unused)) = {0};
    bool _12 __attribute__((unused)) = {0};
    int32_t _13 __attribute__((unused)) = {0};
    uint8_t* _14 __attribute__((unused)) = {0};
    uint8_t* _15 __attribute__((unused)) = {0};
    int64_t _16 __attribute__((unused)) = {0};
    bool _17 __attribute__((unused)) = {0};
    int32_t _18 __attribute__((unused)) = {0};
    int32_t _19 __attribute__((unused)) = {0};
    bool _21 __attribute__((unused)) = {0};
    int32_t _22 __attribute__((unused)) = {0};
    int32_t _23 __attribute__((unused)) = {0};
    int32_t _24 __attribute__((unused)) = {0};
    int32_t _25 __attribute__((unused)) = {0};
    uint8_t* _26 __attribute__((unused)) = {0};
    int64_t _27 __attribute__((unused)) = {0};
    uint8_t* _28 __attribute__((unused)) = {0};
    uint8_t* _29 __attribute__((unused)) = {0};
    int32_t _30 __attribute__((unused)) = {0};
    int32_t _31 __attribute__((unused)) = {0};
    int32_t _32 __attribute__((unused)) = {0};
    int32_t _33 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 403 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
#line 404 "rt\compat_runtime_windows.w"
    /* StorageLive(_5); */
    _6 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _5 = _6;
#line 405 "rt\compat_runtime_windows.w"
    _7 = ((int64_t)(_5));
    _8 = (_7 == 0);
    if (_8 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 406 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 407 "rt\compat_runtime_windows.w"
    /* StorageLive(_9); */
    _10 = str_to_c_buf__115(_2);
    goto bb6;
bb5:
    goto bb4;
bb6:
    _9 = _10;
#line 408 "rt\compat_runtime_windows.w"
    _11 = ((int64_t)(_9));
    _12 = (_11 == 0);
    if (_12 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    with_free(_5);
    goto bb10;
bb8:
    goto bb9;
bb9:
#line 411 "rt\compat_runtime_windows.w"
    /* StorageLive(_14); */
    _15 = str_to_c_buf__115(_3);
    goto bb12;
bb10:
#line 410 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb11:
    goto bb9;
bb12:
#line 411 "rt\compat_runtime_windows.w"
    _14 = _15;
#line 412 "rt\compat_runtime_windows.w"
    _16 = ((int64_t)(_14));
    _17 = (_16 == 0);
    if (_17 == 1) {
        goto bb13;
    }
    else {
        goto bb14;
    }
bb13:
    with_free(_5);
    goto bb16;
bb14:
    goto bb15;
bb15:
#line 416 "rt\compat_runtime_windows.w"
    _21 = (__with_global_interrupt_flag__108 != 0);
    if (_21 == 1) {
        goto bb19;
    }
    else {
        goto bb20;
    }
bb16:
    with_free(_9);
    goto bb17;
bb17:
#line 415 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb18:
    goto bb15;
bb19:
    with_free(_5);
    goto bb22;
bb20:
    goto bb21;
bb21:
#line 421 "rt\compat_runtime_windows.w"
    /* StorageLive(_25); */
    _26 = (uint8_t*)((uint8_t*)(_5));
    _27 = ((_1).len);
    goto bb26;
bb22:
    with_free(_9);
    goto bb23;
bb23:
    with_free(_14);
    goto bb24;
bb24:
#line 420 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb25:
    goto bb21;
bb26:
#line 421 "rt\compat_runtime_windows.w"
    _28 = (uint8_t*)((uint8_t*)(_9));
    _29 = (uint8_t*)((uint8_t*)(_14));
    _30 = run_argv_capture__171(_26, _27, _28, _29, _4);
    goto bb27;
bb27:
    _25 = _30;
    with_free(_5);
    goto bb28;
bb28:
    with_free(_9);
    goto bb29;
bb29:
    with_free(_14);
    goto bb30;
bb30:
#line 425 "rt\compat_runtime_windows.w"
    _0 = _25;
    return _0;
bb31: ;
bb32: ;
bb33: ;
bb34: ;
bb35: ;
bb36: ;
bb37: ;
bb38: ;
bb39: ;
bb40: ;
bb41: ;
bb42: ;
bb43: ;
bb44: ;
bb45: ;
bb46: ;
bb47: ;
bb48: ;
bb49: ;
bb50: ;
bb51: ;
bb52: ;
}

int32_t with_exec_argv_capture_input(with_str _1, with_str _2, with_str _3, int32_t _4, with_str _5) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    int64_t _8 __attribute__((unused)) = {0};
    bool _9 __attribute__((unused)) = {0};
    uint8_t* _10 __attribute__((unused)) = {0};
    uint8_t* _11 __attribute__((unused)) = {0};
    int64_t _12 __attribute__((unused)) = {0};
    bool _13 __attribute__((unused)) = {0};
    int32_t _14 __attribute__((unused)) = {0};
    uint8_t* _15 __attribute__((unused)) = {0};
    uint8_t* _16 __attribute__((unused)) = {0};
    int64_t _17 __attribute__((unused)) = {0};
    bool _18 __attribute__((unused)) = {0};
    int32_t _19 __attribute__((unused)) = {0};
    int32_t _20 __attribute__((unused)) = {0};
    uint8_t* _21 __attribute__((unused)) = {0};
    uint8_t* _22 __attribute__((unused)) = {0};
    int64_t _23 __attribute__((unused)) = {0};
    bool _24 __attribute__((unused)) = {0};
    int32_t _25 __attribute__((unused)) = {0};
    int32_t _26 __attribute__((unused)) = {0};
    int32_t _27 __attribute__((unused)) = {0};
    bool _29 __attribute__((unused)) = {0};
    int32_t _30 __attribute__((unused)) = {0};
    int32_t _31 __attribute__((unused)) = {0};
    int32_t _32 __attribute__((unused)) = {0};
    int32_t _33 __attribute__((unused)) = {0};
    int32_t _34 __attribute__((unused)) = {0};
    uint8_t* _35 __attribute__((unused)) = {0};
    int64_t _36 __attribute__((unused)) = {0};
    uint8_t* _37 __attribute__((unused)) = {0};
    uint8_t* _38 __attribute__((unused)) = {0};
    uint8_t* _39 __attribute__((unused)) = {0};
    int32_t _40 __attribute__((unused)) = {0};
    int32_t _41 __attribute__((unused)) = {0};
    int32_t _42 __attribute__((unused)) = {0};
    int32_t _43 __attribute__((unused)) = {0};
    int32_t _44 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 428 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
    /* StorageLive(_5); */
#line 429 "rt\compat_runtime_windows.w"
    /* StorageLive(_6); */
    _7 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _6 = _7;
#line 430 "rt\compat_runtime_windows.w"
    _8 = ((int64_t)(_6));
    _9 = (_8 == 0);
    if (_9 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 431 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 432 "rt\compat_runtime_windows.w"
    /* StorageLive(_10); */
    _11 = str_to_c_buf__115(_2);
    goto bb6;
bb5:
    goto bb4;
bb6:
    _10 = _11;
#line 433 "rt\compat_runtime_windows.w"
    _12 = ((int64_t)(_10));
    _13 = (_12 == 0);
    if (_13 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    with_free(_6);
    goto bb10;
bb8:
    goto bb9;
bb9:
#line 436 "rt\compat_runtime_windows.w"
    /* StorageLive(_15); */
    _16 = str_to_c_buf__115(_3);
    goto bb12;
bb10:
#line 435 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb11:
    goto bb9;
bb12:
#line 436 "rt\compat_runtime_windows.w"
    _15 = _16;
#line 437 "rt\compat_runtime_windows.w"
    _17 = ((int64_t)(_15));
    _18 = (_17 == 0);
    if (_18 == 1) {
        goto bb13;
    }
    else {
        goto bb14;
    }
bb13:
    with_free(_6);
    goto bb16;
bb14:
    goto bb15;
bb15:
#line 441 "rt\compat_runtime_windows.w"
    /* StorageLive(_21); */
    _22 = str_to_c_buf__115(_5);
    goto bb19;
bb16:
    with_free(_10);
    goto bb17;
bb17:
#line 440 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb18:
    goto bb15;
bb19:
#line 441 "rt\compat_runtime_windows.w"
    _21 = _22;
#line 442 "rt\compat_runtime_windows.w"
    _23 = ((int64_t)(_21));
    _24 = (_23 == 0);
    if (_24 == 1) {
        goto bb20;
    }
    else {
        goto bb21;
    }
bb20:
    with_free(_6);
    goto bb23;
bb21:
    goto bb22;
bb22:
#line 447 "rt\compat_runtime_windows.w"
    _29 = (__with_global_interrupt_flag__108 != 0);
    if (_29 == 1) {
        goto bb27;
    }
    else {
        goto bb28;
    }
bb23:
    with_free(_10);
    goto bb24;
bb24:
    with_free(_15);
    goto bb25;
bb25:
#line 446 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb26:
    goto bb22;
bb27:
    with_free(_6);
    goto bb30;
bb28:
    goto bb29;
bb29:
#line 453 "rt\compat_runtime_windows.w"
    /* StorageLive(_34); */
    _35 = (uint8_t*)((uint8_t*)(_6));
    _36 = ((_1).len);
    goto bb35;
bb30:
    with_free(_10);
    goto bb31;
bb31:
    with_free(_15);
    goto bb32;
bb32:
    with_free(_21);
    goto bb33;
bb33:
#line 452 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb34:
    goto bb29;
bb35:
#line 453 "rt\compat_runtime_windows.w"
    _37 = (uint8_t*)((uint8_t*)(_10));
    _38 = (uint8_t*)((uint8_t*)(_15));
    _39 = (uint8_t*)((uint8_t*)(_21));
    _40 = run_argv_capture_input__172(_35, _36, _37, _38, _4, _39);
    goto bb36;
bb36:
    _34 = _40;
    with_free(_6);
    goto bb37;
bb37:
    with_free(_10);
    goto bb38;
bb38:
    with_free(_15);
    goto bb39;
bb39:
    with_free(_21);
    goto bb40;
bb40:
#line 458 "rt\compat_runtime_windows.w"
    _0 = _34;
    return _0;
bb41: ;
bb42: ;
bb43: ;
bb44: ;
bb45: ;
bb46: ;
bb47: ;
bb48: ;
bb49: ;
bb50: ;
bb51: ;
bb52: ;
bb53: ;
bb54: ;
bb55: ;
bb56: ;
bb57: ;
bb58: ;
bb59: ;
bb60: ;
bb61: ;
bb62: ;
bb63: ;
bb64: ;
bb65: ;
bb66: ;
bb67: ;
bb68: ;
bb69: ;
bb70: ;
bb71: ;
}

int32_t with_exec_argv_capture_cwd(with_str _1, with_str _2, with_str _3, int32_t _4, with_str _5) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _6 __attribute__((unused)) = {0};
    uint8_t* _7 __attribute__((unused)) = {0};
    int64_t _8 __attribute__((unused)) = {0};
    bool _9 __attribute__((unused)) = {0};
    uint8_t* _10 __attribute__((unused)) = {0};
    uint8_t* _11 __attribute__((unused)) = {0};
    int64_t _12 __attribute__((unused)) = {0};
    bool _13 __attribute__((unused)) = {0};
    int32_t _14 __attribute__((unused)) = {0};
    uint8_t* _15 __attribute__((unused)) = {0};
    uint8_t* _16 __attribute__((unused)) = {0};
    int64_t _17 __attribute__((unused)) = {0};
    bool _18 __attribute__((unused)) = {0};
    int32_t _19 __attribute__((unused)) = {0};
    int32_t _20 __attribute__((unused)) = {0};
    uint8_t* _21 __attribute__((unused)) = {0};
    uint8_t* _22 __attribute__((unused)) = {0};
    int64_t _23 __attribute__((unused)) = {0};
    bool _24 __attribute__((unused)) = {0};
    int32_t _25 __attribute__((unused)) = {0};
    int32_t _26 __attribute__((unused)) = {0};
    int32_t _27 __attribute__((unused)) = {0};
    bool _29 __attribute__((unused)) = {0};
    int32_t _30 __attribute__((unused)) = {0};
    int32_t _31 __attribute__((unused)) = {0};
    int32_t _32 __attribute__((unused)) = {0};
    int32_t _33 __attribute__((unused)) = {0};
    int32_t _34 __attribute__((unused)) = {0};
    uint8_t* _35 __attribute__((unused)) = {0};
    int64_t _36 __attribute__((unused)) = {0};
    uint8_t* _37 __attribute__((unused)) = {0};
    uint8_t* _38 __attribute__((unused)) = {0};
    uint8_t* _39 __attribute__((unused)) = {0};
    uint8_t* _40 __attribute__((unused)) = {0};
    int32_t _41 __attribute__((unused)) = {0};
    int32_t _42 __attribute__((unused)) = {0};
    int32_t _43 __attribute__((unused)) = {0};
    int32_t _44 __attribute__((unused)) = {0};
    int32_t _45 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 461 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
    /* StorageLive(_4); */
    /* StorageLive(_5); */
#line 462 "rt\compat_runtime_windows.w"
    /* StorageLive(_6); */
    _7 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _6 = _7;
#line 463 "rt\compat_runtime_windows.w"
    _8 = ((int64_t)(_6));
    _9 = (_8 == 0);
    if (_9 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 464 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 465 "rt\compat_runtime_windows.w"
    /* StorageLive(_10); */
    _11 = str_to_c_buf__115(_2);
    goto bb6;
bb5:
    goto bb4;
bb6:
    _10 = _11;
#line 466 "rt\compat_runtime_windows.w"
    _12 = ((int64_t)(_10));
    _13 = (_12 == 0);
    if (_13 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    with_free(_6);
    goto bb10;
bb8:
    goto bb9;
bb9:
#line 469 "rt\compat_runtime_windows.w"
    /* StorageLive(_15); */
    _16 = str_to_c_buf__115(_3);
    goto bb12;
bb10:
#line 468 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb11:
    goto bb9;
bb12:
#line 469 "rt\compat_runtime_windows.w"
    _15 = _16;
#line 470 "rt\compat_runtime_windows.w"
    _17 = ((int64_t)(_15));
    _18 = (_17 == 0);
    if (_18 == 1) {
        goto bb13;
    }
    else {
        goto bb14;
    }
bb13:
    with_free(_6);
    goto bb16;
bb14:
    goto bb15;
bb15:
#line 474 "rt\compat_runtime_windows.w"
    /* StorageLive(_21); */
    _22 = str_to_c_buf__115(_5);
    goto bb19;
bb16:
    with_free(_10);
    goto bb17;
bb17:
#line 473 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb18:
    goto bb15;
bb19:
#line 474 "rt\compat_runtime_windows.w"
    _21 = _22;
#line 475 "rt\compat_runtime_windows.w"
    _23 = ((int64_t)(_21));
    _24 = (_23 == 0);
    if (_24 == 1) {
        goto bb20;
    }
    else {
        goto bb21;
    }
bb20:
    with_free(_6);
    goto bb23;
bb21:
    goto bb22;
bb22:
#line 480 "rt\compat_runtime_windows.w"
    _29 = (__with_global_interrupt_flag__108 != 0);
    if (_29 == 1) {
        goto bb27;
    }
    else {
        goto bb28;
    }
bb23:
    with_free(_10);
    goto bb24;
bb24:
    with_free(_15);
    goto bb25;
bb25:
#line 479 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb26:
    goto bb22;
bb27:
    with_free(_6);
    goto bb30;
bb28:
    goto bb29;
bb29:
#line 486 "rt\compat_runtime_windows.w"
    /* StorageLive(_34); */
    _35 = (uint8_t*)((uint8_t*)(_6));
    _36 = ((_1).len);
    goto bb35;
bb30:
    with_free(_10);
    goto bb31;
bb31:
    with_free(_15);
    goto bb32;
bb32:
    with_free(_21);
    goto bb33;
bb33:
#line 485 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb34:
    goto bb29;
bb35:
#line 486 "rt\compat_runtime_windows.w"
    _37 = (uint8_t*)((uint8_t*)(_10));
    _38 = (uint8_t*)((uint8_t*)(_15));
    _39 = (uint8_t*)((uint8_t*)(0));
    _40 = (uint8_t*)((uint8_t*)(_21));
    _41 = run_argv_capture_cwd__162(_35, _36, _37, _38, _4, _39, _40);
    goto bb36;
bb36:
    _34 = _41;
    with_free(_6);
    goto bb37;
bb37:
    with_free(_10);
    goto bb38;
bb38:
    with_free(_15);
    goto bb39;
bb39:
    with_free(_21);
    goto bb40;
bb40:
#line 491 "rt\compat_runtime_windows.w"
    _0 = _34;
    return _0;
bb41: ;
bb42: ;
bb43: ;
bb44: ;
bb45: ;
bb46: ;
bb47: ;
bb48: ;
bb49: ;
bb50: ;
bb51: ;
bb52: ;
bb53: ;
bb54: ;
bb55: ;
bb56: ;
bb57: ;
bb58: ;
bb59: ;
bb60: ;
bb61: ;
bb62: ;
bb63: ;
bb64: ;
bb65: ;
bb66: ;
bb67: ;
bb68: ;
bb69: ;
bb70: ;
bb71: ;
bb72: ;
}

int32_t with_exec_argv_capture_spawn(with_str _1, with_str _2, with_str _3) {
    int32_t _0 __attribute__((unused)) = {0};
    uint8_t* _4 __attribute__((unused)) = {0};
    uint8_t* _5 __attribute__((unused)) = {0};
    int64_t _6 __attribute__((unused)) = {0};
    bool _7 __attribute__((unused)) = {0};
    uint8_t* _8 __attribute__((unused)) = {0};
    uint8_t* _9 __attribute__((unused)) = {0};
    int64_t _10 __attribute__((unused)) = {0};
    bool _11 __attribute__((unused)) = {0};
    int32_t _12 __attribute__((unused)) = {0};
    uint8_t* _13 __attribute__((unused)) = {0};
    uint8_t* _14 __attribute__((unused)) = {0};
    int64_t _15 __attribute__((unused)) = {0};
    bool _16 __attribute__((unused)) = {0};
    int32_t _17 __attribute__((unused)) = {0};
    int32_t _18 __attribute__((unused)) = {0};
    bool _20 __attribute__((unused)) = {0};
    int32_t _21 __attribute__((unused)) = {0};
    int32_t _22 __attribute__((unused)) = {0};
    int32_t _23 __attribute__((unused)) = {0};
    int32_t _24 __attribute__((unused)) = {0};
    uint8_t* _25 __attribute__((unused)) = {0};
    int64_t _26 __attribute__((unused)) = {0};
    uint8_t* _27 __attribute__((unused)) = {0};
    uint8_t* _28 __attribute__((unused)) = {0};
    int32_t _29 __attribute__((unused)) = {0};
    int32_t _30 __attribute__((unused)) = {0};
    int32_t _31 __attribute__((unused)) = {0};
    int32_t _32 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 494 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
    /* StorageLive(_3); */
#line 495 "rt\compat_runtime_windows.w"
    /* StorageLive(_4); */
    _5 = str_to_c_buf__115(_1);
    goto bb1;
bb1:
    _4 = _5;
#line 496 "rt\compat_runtime_windows.w"
    _6 = ((int64_t)(_4));
    _7 = (_6 == 0);
    if (_7 == 1) {
        goto bb2;
    }
    else {
        goto bb3;
    }
bb2:
#line 497 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb3:
    goto bb4;
bb4:
#line 498 "rt\compat_runtime_windows.w"
    /* StorageLive(_8); */
    _9 = str_to_c_buf__115(_2);
    goto bb6;
bb5:
    goto bb4;
bb6:
    _8 = _9;
#line 499 "rt\compat_runtime_windows.w"
    _10 = ((int64_t)(_8));
    _11 = (_10 == 0);
    if (_11 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
    with_free(_4);
    goto bb10;
bb8:
    goto bb9;
bb9:
#line 502 "rt\compat_runtime_windows.w"
    /* StorageLive(_13); */
    _14 = str_to_c_buf__115(_3);
    goto bb12;
bb10:
#line 501 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb11:
    goto bb9;
bb12:
#line 502 "rt\compat_runtime_windows.w"
    _13 = _14;
#line 503 "rt\compat_runtime_windows.w"
    _15 = ((int64_t)(_13));
    _16 = (_15 == 0);
    if (_16 == 1) {
        goto bb13;
    }
    else {
        goto bb14;
    }
bb13:
    with_free(_4);
    goto bb16;
bb14:
    goto bb15;
bb15:
#line 507 "rt\compat_runtime_windows.w"
    _20 = (__with_global_interrupt_flag__108 != 0);
    if (_20 == 1) {
        goto bb19;
    }
    else {
        goto bb20;
    }
bb16:
    with_free(_8);
    goto bb17;
bb17:
#line 506 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb18:
    goto bb15;
bb19:
    with_free(_4);
    goto bb22;
bb20:
    goto bb21;
bb21:
#line 512 "rt\compat_runtime_windows.w"
    /* StorageLive(_24); */
    _25 = (uint8_t*)((uint8_t*)(_4));
    _26 = ((_1).len);
    goto bb26;
bb22:
    with_free(_8);
    goto bb23;
bb23:
    with_free(_13);
    goto bb24;
bb24:
#line 511 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb25:
    goto bb21;
bb26:
#line 512 "rt\compat_runtime_windows.w"
    _27 = (uint8_t*)((uint8_t*)(_8));
    _28 = (uint8_t*)((uint8_t*)(_13));
    _29 = spawn_argv_capture__169(_25, _26, _27, _28);
    goto bb27;
bb27:
    _24 = _29;
    with_free(_4);
    goto bb28;
bb28:
    with_free(_8);
    goto bb29;
bb29:
    with_free(_13);
    goto bb30;
bb30:
#line 516 "rt\compat_runtime_windows.w"
    _0 = _24;
    return _0;
bb31: ;
bb32: ;
bb33: ;
bb34: ;
bb35: ;
bb36: ;
bb37: ;
bb38: ;
bb39: ;
bb40: ;
bb41: ;
bb42: ;
bb43: ;
bb44: ;
bb45: ;
bb46: ;
bb47: ;
bb48: ;
bb49: ;
bb50: ;
bb51: ;
}

int32_t with_exec_wait(int32_t _1, int32_t _2) {
    int32_t _0 __attribute__((unused)) = {0};
    bool _3 __attribute__((unused)) = {0};
    int64_t _4 __attribute__((unused)) = {0};
    bool _6 __attribute__((unused)) = {0};
    bool _7 __attribute__((unused)) = {0};
    bool _8 __attribute__((unused)) = {0};
    int32_t _9 __attribute__((unused)) = {0};
    int32_t _10 __attribute__((unused)) = {0};
    goto bb0;
bb0:
#line 519 "rt\compat_runtime_windows.w"
    /* StorageLive(_1); */
    /* StorageLive(_2); */
#line 520 "rt\compat_runtime_windows.w"
    _3 = (_1 <= 0);
    if (_3 == 1) {
        goto bb1;
    }
    else {
        goto bb2;
    }
bb1:
#line 521 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb2:
    goto bb3;
bb3:
#line 524 "rt\compat_runtime_windows.w"
    /* StorageLive(_4); */
    _4 = __with_global_last_spawned_handle__109;
#line 525 "rt\compat_runtime_windows.w"
    _7 = (_4 == 0);
    _6 = _7;
    if (_6 == 1) {
        goto bb6;
    }
    else {
        goto bb5;
    }
bb4:
    goto bb3;
bb5:
    _8 = (_4 == -1);
    _6 = _8;
    goto bb6;
bb6:
    if (_6 == 1) {
        goto bb7;
    }
    else {
        goto bb8;
    }
bb7:
#line 526 "rt\compat_runtime_windows.w"
    _0 = -1;
    return _0;
bb8:
    goto bb9;
bb9:
#line 527 "rt\compat_runtime_windows.w"
    __with_global_last_spawned_handle__109 = 0;
#line 528 "rt\compat_runtime_windows.w"
    /* StorageLive(_9); */
    _10 = wait_for_process_timeout__147(_4, -1, _2);
    goto bb11;
bb10:
    goto bb9;
bb11:
    _9 = _10;
#line 529 "rt\compat_runtime_windows.w"
    _0 = _9;
    return _0;
bb12: ;
bb13: ;
bb14: ;
bb15: ;
bb16: ;
bb17: ;
}

