#ifndef WITH_FILTERED_H
#define WITH_FILTERED_H
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
typedef struct { const uint8_t *ptr; int64_t len; } with_str;
typedef struct { void *ptr; int64_t len; int64_t cap; int64_t elem_size; } with_vec;
typedef struct { bool has_value; int32_t value; } with_option_i32;
typedef struct { bool has_value; int64_t value; } with_option_i64;
typedef struct { bool has_value; with_str value; } with_option_str;
typedef struct Captures Captures;
#define WITH_STR_LIT(s) ((with_str){(const uint8_t*)(s), (int64_t)(sizeof(s) - 1)})
#define with_len(v) ((v).len)
#define with_is_empty(v) (((v).len == 0) ? 1 : 0)
with_str with_str_from_byte(int32_t _1);
int64_t with_fmt_buf_write_f64(uint8_t* _1, double _2);
with_str with_fmt_u32(uint32_t _1);
int64_t with_bswap64(int64_t _1);
int32_t with_abs(int32_t _1);
int64_t with_str_index_of(with_str _1, with_str _2);
int32_t with_getpid();
void with_eprint(with_str _1);
uint8_t* with_hashmap_new(int64_t _1, int64_t _2);
void with_free_sized(uint8_t* _1, int64_t _2);
int64_t with_hashmap_insert(uint8_t* _1, uint8_t* _2, uint8_t* _3, int64_t _4);
int32_t with_hashmap_get(uint8_t* _1, uint8_t* _2, uint8_t* _3, int64_t _4);
with_str with_getenv(with_str _1);
int64_t with_vec_get_i64(uint8_t* _1, int64_t _2);
int32_t with_fs_file_exists(with_str _1);
with_str with_sysinfo_os();
void with_runtime_shutdown();
int32_t with_extract_runtime_obj(with_str _1, with_str _2);
int64_t with_codegen_loop_get_result(int32_t _1);
int32_t with_fs_is_dir(with_str _1);
int32_t with_fs_symlink(with_str _1, with_str _2);
with_str with_vec_str_join(uint8_t* _1, with_str _2);
void with_vec_set_i64(uint8_t* _1, int64_t _2, int64_t _3);
void with_assert(int32_t _1, with_str _2);
int64_t with_sb_new();
with_str with_fmt_str_debug(with_str _1);
int64_t with_parse_i64(with_str _1);
with_str with_vec_get_str(uint8_t* _1, int64_t _2);
int32_t with_process_alive(int32_t _1);
with_str with_str_repeat(with_str _1, int64_t _2);
int8_t* with_regex_compile(with_str _1, int32_t _2, int32_t* _3, int32_t* _4);
void with_write_stdout(with_str _1);
int32_t with_fs_create_dir(with_str _1);
int32_t with_net_tcp_connect(with_str _1, int32_t _2);
int32_t with_raise(int32_t _1);
int64_t with_fmt_buf_write_i64(uint8_t* _1, int64_t _2);
void with_lines_out(uint8_t* _1, with_str _2);
int64_t with_hashmap_decrement(uint8_t* _1, uint8_t* _2, int64_t _3);
int32_t with_net_tcp_listen(int32_t _1, int32_t _2);
int64_t with_vec_new(int64_t _1);
void with_hashmap_free(uint8_t* _1);
int64_t with_codegen_loop_get_continue(int32_t _1);
int32_t with_fs_remove_tree(with_str _1);
int16_t with_bswap16(int16_t _1);
int64_t with_thread_spawn(uint8_t* _1, uint8_t* _2);
int32_t with_bswap32(int32_t _1);
int64_t with_str_split_vec(uint8_t* _1, with_str _2, with_str _3);
int32_t with_str_eq(with_str _1, with_str _2);
void with_codegen_loop_set_continue(int32_t _1, int64_t _2);
with_str with_fmt_i64(int64_t _1);
int32_t with_clzll(int64_t _1);
int32_t with_sysinfo(uint8_t* _1);
with_str with_regex_substitute(uint8_t* code, with_str text, with_str repl, int32_t replace_all);
with_str with_str_substr(with_str _1, int64_t _2, int64_t _3);
int64_t with_hashmap_increment(uint8_t* _1, uint8_t* _2, int64_t _3);
with_str with_fmt_u64(uint64_t _1);
with_str with_regex_capture_name_at(uint8_t* code, int32_t index);
with_str with_arg_at(int32_t _1);
void with_println_str(with_str _1);
int32_t with_ctzll(int64_t _1);
int32_t with_str_ends_with(with_str _1, with_str _2);
with_str with_i32_to_str(int32_t _1);
int64_t with_vec_remove(uint8_t* _1, int64_t _2);
with_str with_fmt_int_spec(int64_t _1, int32_t _2, int64_t _3, int32_t _4, int32_t _5, int32_t _6);
int32_t with_ptr_get_i32(uint8_t* _1, int64_t _2);
int32_t with_net_tcp_accept(int32_t _1);
with_str with_fmt_str(with_str _1);
with_str with_sysinfo_hostname();
with_str with_fmt_bool(int32_t _1);
with_str with_str_concat(with_str _1, with_str _2);
int64_t with_hashmap_clear(uint8_t* _1);
int32_t with_regex_capture_name_count(int8_t* _1);
int32_t with_clz(int32_t _1);
void with_vec_set_i32(uint8_t* _1, int64_t _2, int32_t _3);
void with_codegen_loop_set_break(int32_t _1, int64_t _2);
uint8_t* with_vec_get_ptr(uint8_t* _1, int64_t _2);
void with_print_str(with_str _1);
with_str with_str_slice(with_str _1, int64_t _2, int64_t _3);
int8_t* with_regex_code_copy(int8_t* _1);
int32_t with_str_starts_with(with_str _1, with_str _2);
int64_t with_lines(with_str _1);
int64_t with_vec_push(uint8_t* _1, uint8_t* _2);
with_str with_fmt_str_spec(with_str _1, int64_t _2, int32_t _3, int32_t _4);
int64_t with_time_now();
with_str with_fmt_f64(double _1);
int32_t with_fs_mkdir(with_str _1);
void with_println_i64(int64_t _1);
int32_t with_fs_remove_file(with_str _1);
void with_panic_core(with_str _1, with_str _2, int32_t _3);
void with_scope_destroy(int64_t _1);
int64_t with_fmt_buf_write_bool(uint8_t* _1, int32_t _2);
int64_t with_vec_push_bool(uint8_t* _1, int32_t _2);
with_str with_fs_list_files(with_str _1);
void with_flush_stdout();
int32_t with_arg_count();
int32_t* with_regex_match_spans_alloc_at(int8_t* _1, with_str _2, int32_t _3, int32_t* _4);
with_str with_regex_error_message(int32_t code);
int32_t with_str_contains(with_str _1, with_str _2);
with_str with_fmt_i32(int32_t _1);
void with_fmt_buf_write_debug(uint8_t* _1, with_str _2);
int32_t with_fs_write_file(with_str _1, with_str _2);
with_str with_getenv_str(with_str _1);
int32_t with_fs_mkdir_p(with_str _1);
with_str with_i64_to_str(int64_t _1);
void with_eprintln(with_str _1);
with_str with_fs_read_file(with_str _1);
int32_t with_fs_chmod(with_str _1, int32_t _2);
int32_t with_fs_copy_tree(with_str _1, with_str _2);
void with_fill_random(uint8_t* _1, int64_t _2);
with_str with_fmt_f64_spec(double _1, int64_t _2, int32_t _3, int32_t _4, int32_t _5);
void with_write(with_str _1);
int64_t with_fmt_buf_write_char(uint8_t* _1, uint8_t _2);
with_str with_str_trim(with_str _1);
int32_t with_hashmap_remove(uint8_t* _1, uint8_t* _2, uint8_t* _3, int64_t _4);
with_str with_str_from_cstr(uint8_t* _1);
int32_t with_memcmp(uint8_t* _1, uint8_t* _2, int64_t _3);
int64_t with_hashmap_len(uint8_t* _1);
void with_regex_code_free(int8_t* _1);
int32_t with_vec_get_i32(uint8_t* _1, int64_t _2);
int32_t with_thread_join(int64_t _1);
int64_t with_scope_create();
int32_t with_hashmap_contains(uint8_t* _1, uint8_t* _2, int64_t _3);
uint64_t with_str_hash(with_str _1);
with_str with_read_line_stdin();
void with_println_i32(int32_t _1);
int32_t with_net_close(int32_t _1);
with_str with_sb_build(uint8_t* _1);
int32_t with_vec_get_bool(uint8_t* _1, int64_t _2);
void with_codegen_loop_set_result(int32_t _1, int64_t _2);
with_str with_str_join(uint8_t* _1, with_str _2);
with_str with_str_from_bytes(uint8_t* _1, int64_t _2);
int64_t with_vec_new_out(uint8_t* _1, int64_t _2);
void with_runtime_set_argv(int32_t _1, uint8_t** _2);
int32_t with_ctzl(int64_t _1);
int64_t with_vec_clear(uint8_t* _1);
with_str with_str_replace(with_str _1, with_str _2, with_str _3);
with_str with_sysinfo_arch();
int32_t with_clzl(int64_t _1);
with_str with_str_to_lower(with_str _1);
with_str with_str_clone(with_str _1);
void with_runtime_init();
int32_t with_ctz(int32_t _1);
int32_t with_popcount(int32_t _1);
int64_t with_net_send(int32_t _1, with_str _2);
int32_t with_regex_capture_count(int8_t* _1);
int32_t with_scope_track(int64_t _1, int32_t _2);
int64_t with_codegen_loop_get_break(int32_t _1);
int64_t with_vec_push_i64(uint8_t* _1, int64_t _2);
int64_t with_str_split(with_str _1, with_str _2, uint8_t* _3, int64_t* _4);
with_str with_fmt_buf_finish(uint8_t* _1);
int64_t with_sb_append(uint8_t* _1, with_str _2);
with_str with_f64_to_string(double _1);
int32_t with_vec_pop_i32(uint8_t* _1);
with_str with_str_to_upper(with_str _1);
int32_t with_fs_rename_file(with_str _1, with_str _2);
int32_t with_net_udp_bind(int32_t _1);
int64_t with_vec_len(uint8_t* _1);
int32_t with_fs_remove_dir(with_str _1);
void with_scope_await_all(int64_t _1);
int64_t with_vec_push_str(uint8_t* _1, with_str _2);
with_str with_bool_to_str(int32_t _1);
void with_hashmap_keys_out(uint8_t* _1, uint8_t* _2, int64_t _3);
int32_t with_usleep(int32_t _1);
with_str with_read_bytes_stdin(int32_t _1);
int32_t with_regex_group_name_to_index(int8_t* _1, with_str _2);
with_str with_net_recv(int32_t _1, int64_t _2);
int64_t with_vec_push_i32(uint8_t* _1, int32_t _2);
#endif
